from pathlib import Path

app_path=Path('app.js')
app=app_path.read_text(encoding='utf-8')

# Add direct DOM image rendering for favorites. No CSS background/pseudo overlays.
old="function syncFavoriteButtons(id,active){document.querySelectorAll('[data-favorite]').forEach(button=>{if(String(button.dataset.favorite)!==String(id))return;button.classList.toggle('active',active);button.setAttribute('aria-label',active?'Убрать из избранного':'Добавить в избранное')})}\nfunction toggleFavorite(id){const active=!state.favorites.includes(id);state.favorites=active?[...state.favorites,id]:state.favorites.filter(x=>x!==id);storage.write('forma:favorites',state.favorites);updateCounters();if(state.view==='favorites')applyFilters();renderRecent();syncFavoriteButtons(id,active);toast(active?'Добавили в избранное':'Убрали из избранного')}"
new="const FAVORITE_ICON_INACTIVE='assets/ui/favorite-inactive.png',FAVORITE_ICON_ACTIVE='assets/ui/favorite-active.png';\nfunction syncHeaderFavoriteIcon(){const holder=$('#favoritesButton .action-icon');if(!holder)return;let img=holder.querySelector('.favorite-icon-image');if(!img){holder.textContent='';img=document.createElement('img');img.className='favorite-icon-image header-favorite-icon';img.alt='';img.setAttribute('aria-hidden','true');holder.appendChild(img)}if(img.getAttribute('src')!==FAVORITE_ICON_ACTIVE)img.src=FAVORITE_ICON_ACTIVE}\nfunction syncFavoriteButtons(id=null){document.querySelectorAll('[data-favorite]').forEach(button=>{if(id!==null&&String(button.dataset.favorite)!==String(id))return;const active=state.favorites.includes(button.dataset.favorite);button.classList.toggle('active',active);button.setAttribute('aria-label',active?'Убрать из избранного':'Добавить в избранное');let img=button.querySelector('.favorite-icon-image');if(!img){button.textContent='';img=document.createElement('img');img.className='favorite-icon-image';img.alt='';img.setAttribute('aria-hidden','true');button.appendChild(img)}const src=active?FAVORITE_ICON_ACTIVE:FAVORITE_ICON_INACTIVE;if(img.getAttribute('src')!==src)img.src=src});syncHeaderFavoriteIcon()}\nfunction toggleFavorite(id){const active=!state.favorites.includes(id);state.favorites=active?[...state.favorites,id]:state.favorites.filter(x=>x!==id);storage.write('forma:favorites',state.favorites);updateCounters();if(state.view==='favorites')applyFilters();else syncFavoriteButtons(id);renderRecent();syncFavoriteButtons();toast(active?'Добавили в избранное':'Убрали из избранного')}"
if old not in app:
    raise SystemExit('sync/toggle favorite pattern not found')
app=app.replace(old,new,1)

# Hydrate icons after every place that creates favorite buttons.
app=app.replace("els.grid.innerHTML=list.map(cardTemplate).join('');els.empty.hidden=!!list.length;renderPagination()","els.grid.innerHTML=list.map(cardTemplate).join('');syncFavoriteButtons();els.empty.hidden=!!list.length;renderPagination()",1)
app=app.replace("els.detail.innerHTML=detailTemplate(p,currentVariant(p,p._selected));renderRecent()","els.detail.innerHTML=detailTemplate(p,currentVariant(p,p._selected));syncFavoriteButtons();renderRecent()",1)
app=app.replace("els.detail.innerHTML=detailTemplate(p,currentVariant(p,sourceId))","els.detail.innerHTML=detailTemplate(p,currentVariant(p,sourceId));syncFavoriteButtons()",1)
app=app.replace("$('#recentRow').innerHTML=p.map(recentCardTemplate).join('')","$('#recentRow').innerHTML=p.map(recentCardTemplate).join('');syncFavoriteButtons()",1)
app_path.write_text(app,encoding='utf-8')

css_path=Path('card-polish.css')
css=css_path.read_text(encoding='utf-8')
marker='/* FORMA FAVORITE ICON SYSTEM — exact reference assets, direct rendering */'
if marker not in css:
    raise SystemExit('favorite CSS marker not found')
head=css.split(marker,1)[0].rstrip()+'\n'
component='''/* FORMA FAVORITE ICON SYSTEM — exact reference assets as real image elements */
:root{--cart-trolley-image:url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 64 64'%3E%3Cpath d='M7 11h8l6 30h28l7-21H20' fill='none' stroke='%2320201d' stroke-width='4' stroke-linecap='round' stroke-linejoin='round'/%3E%3Cpath d='M24 49h25' fill='none' stroke='%2320201d' stroke-width='4' stroke-linecap='round'/%3E%3Ccircle cx='27' cy='55' r='3.6' fill='%2320201d'/%3E%3Ccircle cx='48' cy='55' r='3.6' fill='%2320201d'/%3E%3C/svg%3E")}
button[data-favorite]{padding:0!important;border:0!important;background:transparent!important;box-shadow:none!important;backdrop-filter:none!important;color:transparent!important;font-size:0!important;line-height:0!important;overflow:visible!important;opacity:1!important;cursor:pointer!important;pointer-events:auto!important}
button[data-favorite]::before,button[data-favorite]::after{content:none!important;display:none!important}
.favorite-icon-image{display:block!important;width:42px!important;height:auto!important;max-width:none!important;max-height:none!important;object-fit:contain!important;pointer-events:none!important;user-select:none!important}
.product-visual-controls .favorite{position:absolute!important;z-index:8!important;right:10px!important;left:auto!important;top:10px!important;width:48px!important;height:52px!important;min-width:48px!important;min-height:52px!important;display:grid!important;place-items:center!important}
.recent-favorite{position:absolute!important;z-index:8!important;right:8px!important;left:auto!important;top:8px!important;width:44px!important;height:48px!important;min-width:44px!important;min-height:48px!important;display:grid!important;place-items:center!important}.recent-favorite .favorite-icon-image{width:38px!important}
.detail-favorite{position:relative!important;width:56px!important;height:60px!important;min-width:56px!important;min-height:60px!important;display:grid!important;place-items:center!important}.detail-favorite .favorite-icon-image{width:48px!important}
.site-header,.site-header .header-actions{overflow:visible!important}.site-header .favorites-button{position:relative!important;display:flex!important;align-items:center!important;justify-content:flex-start!important;gap:7px!important;width:auto!important;min-width:154px!important;height:50px!important;min-height:50px!important;padding:0 14px 0 7px!important;border:1px solid #d7dfd3!important;border-radius:15px!important;background:#fff!important;color:#20201d!important;box-shadow:0 6px 18px rgba(49,77,50,.08)!important;overflow:visible!important;font-weight:750!important}.site-header .favorites-button::before{content:none!important}.site-header .favorites-button::after{content:"Избранное"!important;font-size:14px;font-weight:750;line-height:1;color:#20201d}.site-header .favorites-button .action-icon{position:relative!important;z-index:4!important;display:grid!important;place-items:center!important;flex:0 0 58px!important;width:58px!important;height:64px!important;margin:-8px 0 -8px -7px!important;overflow:visible!important;color:transparent!important;font-size:0!important;-webkit-text-stroke:0!important;pointer-events:none!important}.site-header .favorites-button .header-favorite-icon{width:54px!important;height:auto!important}.site-header .favorites-button:hover{background:#f7f5f0!important}
.site-header .cart-button{position:relative!important;display:grid!important;place-items:center!important;width:50px!important;min-width:50px!important;height:50px!important;min-height:50px!important;padding:0!important;border:1px solid #d7dfd3!important;border-radius:15px!important;background:#fff!important;color:#20201d!important;box-shadow:0 6px 18px rgba(49,77,50,.08)!important}.site-header .cart-icon{display:block!important;width:30px!important;height:30px!important;background:var(--cart-trolley-image) center/contain no-repeat!important;font-size:0!important;-webkit-text-stroke:0!important}.site-header .cart-icon::before,.site-header .cart-icon::after{content:none!important;display:none!important}.site-header .action-count{z-index:9!important;top:-6px!important;right:-6px!important;background:#435d41!important;color:#fff!important;border:2px solid #f7f5f0!important}
@media(max-width:640px){.product-visual-controls .favorite{right:7px!important;top:7px!important;width:44px!important;height:48px!important;min-width:44px!important;min-height:48px!important}.product-visual-controls .favorite .favorite-icon-image{width:38px!important}.recent-favorite{width:40px!important;height:44px!important;min-width:40px!important;min-height:44px!important}.recent-favorite .favorite-icon-image{width:34px!important}.detail-favorite{width:52px!important;height:56px!important;min-width:52px!important;min-height:56px!important}.detail-favorite .favorite-icon-image{width:44px!important}.site-header .favorites-button{min-width:132px!important;height:46px!important;min-height:46px!important;padding-right:9px!important}.site-header .favorites-button .action-icon{flex-basis:50px!important;width:50px!important;height:58px!important;margin:-6px 0 -6px -6px!important}.site-header .favorites-button .header-favorite-icon{width:48px!important}.site-header .favorites-button::after{font-size:12px}.site-header .cart-button{width:46px!important;min-width:46px!important;height:46px!important;min-height:46px!important}.site-header .cart-icon{width:28px!important;height:28px!important}}
'''
css_path.write_text(head+component,encoding='utf-8')
