from pathlib import Path
import re

# 1) Make favorite controls use one real text glyph, not pseudo/image layers.
app_path=Path('app.js')
app=app_path.read_text(encoding='utf-8')

# Any favorite button generated by templates: put the actual heart inside the button.
app=re.sub(r'(data-favorite=\\"\$\{escapeAttr\(p\.id\)\}\\" aria-label=\\"\$\{favorite\?\'Убрать из избранного\':\'Добавить в избранное\'\}\\">)(</button>)',r"\1${favorite?'♥':'♡'}\2",app)

# Keep state, aria and visible glyph synchronized without rerendering the catalog.
old="function syncFavoriteButtons(id=null){document.querySelectorAll('[data-favorite]').forEach(button=>{if(id!==null&&String(button.dataset.favorite)!==String(id))return;const active=state.favorites.includes(button.dataset.favorite);button.classList.toggle('active',active);button.setAttribute('aria-label',active?'Убрать из избранного':'Добавить в избранное')})}"
new="function syncFavoriteButtons(id=null){document.querySelectorAll('[data-favorite]').forEach(button=>{if(id!==null&&String(button.dataset.favorite)!==String(id))return;const active=state.favorites.includes(button.dataset.favorite);button.classList.toggle('active',active);button.setAttribute('aria-label',active?'Убрать из избранного':'Добавить в избранное');button.textContent=active?'♥':'♡'})}"
if old not in app:
    raise SystemExit('syncFavoriteButtons pattern not found')
app=app.replace(old,new,1)

# Favorite and quick-add are independent actions: handle them before product opening.
old="if(b.dataset.favorite){e.preventDefault();e.stopPropagation();toggleFavorite(b.dataset.favorite);return}if(b.dataset.open)await openProduct(b.dataset.open);if(b.dataset.cardVariant){e.stopPropagation();const p=state.products.find(x=>x.id===b.dataset.product);if(p){p._selected=b.dataset.cardVariant;renderCatalog()}}if(b.dataset.add){e.stopPropagation();addToCart(b.dataset.add,b.dataset.source)}"
new="if(b.dataset.favorite){e.preventDefault();e.stopPropagation();toggleFavorite(b.dataset.favorite);return}if(b.dataset.add){e.preventDefault();e.stopPropagation();addToCart(b.dataset.add,b.dataset.source);return}if(b.dataset.open)await openProduct(b.dataset.open);if(b.dataset.cardVariant){e.stopPropagation();const p=state.products.find(x=>x.id===b.dataset.product);if(p){p._selected=b.dataset.cardVariant;renderCatalog()}}"
if old not in app:
    raise SystemExit('click order pattern not found')
app=app.replace(old,new,1)
app_path.write_text(app,encoding='utf-8')

# 2) Header: one normal heart, no generated duplicate.
index_path=Path('index.html')
html=index_path.read_text(encoding='utf-8')
html=html.replace('<span class="action-icon" aria-hidden="true"></span><span class="sr-only">Избранное</span>','<span class="action-icon" aria-hidden="true">♥</span><span class="sr-only">Избранное</span>',1)
index_path.write_text(html,encoding='utf-8')

# 3) Remove the experimental favorite section and replace it with one small, direct component.
css_path=Path('card-polish.css')
css=css_path.read_text(encoding='utf-8')
for marker in [
    '/* FORMA FAVORITE CONTROLS — simple native hearts, no image layers */',
    '/* FORMA FAVORITE ICON SYSTEM — exact reference assets as real image elements */',
    '/* FORMA FAVORITE ICON SYSTEM — exact reference assets, direct rendering */'
]:
    if marker in css:
        css=css.split(marker,1)[0].rstrip()+'\n'
        break
component='''/* FORMA FAVORITES — single native control, no visual layers */
button[data-favorite]{display:grid!important;place-items:center!important;padding:0!important;border:0!important;background:rgba(255,255,255,.88)!important;box-shadow:none!important;color:#b74736!important;font-family:Arial,Helvetica,sans-serif!important;font-size:30px!important;font-weight:400!important;line-height:1!important;-webkit-text-stroke:0!important;text-shadow:none!important;cursor:pointer!important;pointer-events:auto!important;overflow:visible!important}
button[data-favorite]::before,button[data-favorite]::after{content:none!important;display:none!important}
button[data-favorite].active{background:rgba(255,255,255,.94)!important;color:#b74736!important}
.product-visual-controls .favorite{position:absolute!important;z-index:8!important;right:10px!important;left:auto!important;top:10px!important;width:40px!important;height:40px!important;min-width:40px!important;min-height:40px!important;border-radius:50%!important}
.recent-favorite{position:absolute!important;z-index:8!important;right:8px!important;left:auto!important;top:8px!important;width:36px!important;height:36px!important;min-width:36px!important;min-height:36px!important;border-radius:50%!important;font-size:27px!important}
.detail-favorite{width:48px!important;height:48px!important;min-width:48px!important;min-height:48px!important;border:1px solid #cbd7c7!important;border-radius:12px!important;background:#fff!important;font-size:32px!important}
.site-header .favorites-button .action-icon::before,.site-header .favorites-button .action-icon::after{content:none!important;display:none!important}
.site-header .favorites-button .action-icon{display:grid!important;place-items:center!important;color:#b74736!important;font-family:Arial,Helvetica,sans-serif!important;font-size:30px!important;font-weight:400!important;line-height:1!important;-webkit-text-stroke:0!important}
@media(max-width:640px){.product-visual-controls .favorite{right:8px!important;top:8px!important;width:36px!important;height:36px!important;min-width:36px!important;min-height:36px!important;font-size:27px!important}.recent-favorite{width:34px!important;height:34px!important;min-width:34px!important;min-height:34px!important;font-size:25px!important}}
'''
css_path.write_text(css+component,encoding='utf-8')
