const DATA_BASE='./data/',ASSET_BASE='https://gkkm8bm7rn-eng.github.io/tetopt/',ORDER_EMAIL='postes@mail.ru',PAGE_SIZE=24;
const storage={read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const state={products:[],filtered:[],categoryAssignments:{},categoryMain:'all',categoryCode:'all',search:'',sort:'featured',page:1,min:'',max:'',multi:false,view:'catalog',favorites:storage.read('forma:favorites',[]),cart:storage.read('forma:cart',{}),recent:storage.read('forma:recent',[]),detailCache:new Map()};
const $=(s,r=document)=>r.querySelector(s),els={grid:$('#productGrid'),count:$('#resultCount'),title:$('#catalogTitle'),categories:$('#categoryRow'),pages:$('#pagination'),empty:$('#emptyState'),detail:$('#productDetail'),productDialog:$('#productDialog'),cartDialog:$('#cartDialog'),cartItems:$('#cartItems'),cartFooter:$('#cartFooter'),toast:$('#toast'),favoritesToolbar:$('#favoritesToolbar'),shareFavorites:$('#shareFavorites')};
const stripPackaging=(n='')=>String(n).replace(/\(\s*\d+\s*(?:шт\.?|штук)\s*(?:в\s*(?:\d+\s*(?:[-–—]\s*х)?\s*)?)?(?:упаковк[а-яёa-z]*|уп\.?)\s*\)/giu,' ').replace(/,\s*\d+\s*(?:шт\.?|штук)\s*(?:в\s*(?:\d+\s*(?:[-–—]\s*х)?\s*)?)?(?:упаковк[а-яёa-z]*|уп\.?)\s*\)/giu,')').replace(/(?:\s*[\[(/,-]?\s*)\d+\s*(?:шт\.?|штук)\s*(?:в\s*(?:\d+\s*(?:[-–—]\s*х)?\s*)?)?(?:упаковк[а-яёa-z]*|уп\.?)/giu,' ').replace(/\s+/g,' ').trim();
const money=v=>new Intl.NumberFormat('ru-RU').format(Number(v)||0)+' ₽',imageUrl=p=>!p?'':/^https?:/.test(p)?p:ASSET_BASE+String(p).replace(/^\//,''),stripModel=(n='')=>stripPackaging(n).replace(/\s*\(мод\.[^)]+\)\s*/gi,' ').replace(/\s+/g,' ').trim();
const currentVariant=(p,id)=>p.variants.find(v=>String(v.sourceId)===String(id))||p.variants[0],minPrice=p=>Math.min(...p.variants.map(v=>Number(v.wholesalePrice)||Infinity));
const variantLabel=v=>v.label||(v.specs||'').split(',').map(s=>s.trim()).filter(Boolean).slice(-2).join(' · ')||`Вариант ${v.sourceId}`;
function sleepingSize(product,variant){
  if(!/^\s*кровать(?:\s|$)/i.test(product.name||''))return'';
  const match=`${variant.specs||''} ${variant.label||''}`.match(/(\d{2,3}(?:[.,]\d+)?\s*[хx×]\s*\d{2,3}(?:[.,]\d+)?)\s*см/i);
  return match?match[1].replace(/\s*[хx×]\s*/i,' × ').replace(/\s+/g,' ').trim()+' см':'';
}
const plural=(n,a,b,c)=>n%100>=11&&n%100<=14?c:n%10===1?a:n%10>=2&&n%10<=4?b:c,escapeHtml=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),escapeAttr=escapeHtml;
const hashParams=()=>new URLSearchParams(location.hash.replace(/^#/,'')),baseUrl=()=>location.href.split('#')[0];
if('scrollRestoration'in history)history.scrollRestoration='manual';

const CATEGORY_TREE=[
  {id:'interior',label:'Интерьерная мебель',icon:'⌂',codes:['1','2','14','15','16','7','8','5','3','6','11','4','13'],children:[['1','Стулья'],['2','Барные и полубарные стулья'],['14','Обеденные столы'],['15','Журнальные и кофейные столы'],['16','Письменные столы'],['7','Комоды и тумбы'],['8','Шкафы и стеллажи'],['5','Диваны'],['3','Кресла'],['6','Модульная мягкая мебель'],['11','Кровати'],['4','Пуфы, банкетки и табуреты'],['13','Декор и аксессуары']]},
  {id:'outdoor',label:'Садовая мебель',icon:'♧',codes:['9','10'],children:[['9','Мебель из металла'],['10','Мебель из ротанга']]},
  {id:'horeca',label:'Мебель для HoReCa',icon:'▦',codes:['18'],children:[]},
  {id:'office',label:'Офисные кресла',icon:'◒',codes:['12'],children:[]}
];
const MOBILE_CATEGORY_LABELS={all:'Все',interior:'Интерьер',outdoor:'Сад',horeca:'HoReCa',office:'Офисные кресла'};
const MOBILE_ALL_LABELS={interior:'Вся интерьерная мебель',outdoor:'Вся садовая мебель',horeca:'Вся мебель для HoReCa',office:'Все офисные кресла'};
let expandedMobileCategory=null;
const CATEGORY_BY_CODE=new Map(CATEGORY_TREE.flatMap(main=>main.codes.map(code=>[code,{main,label:main.children.find(child=>child[0]===code)?.[1]||main.label}])));
const categoryCodes=product=>(product.categoryCodes||[]).map(String);
const categoryMainFor=code=>CATEGORY_BY_CODE.get(String(code))?.main;
const categoryLabel=code=>CATEGORY_BY_CODE.get(String(code))?.label||'';
function currentCatalogTitle(){
  if(state.view==='favorites')return'Избранное';
  if(state.search.trim())return`Поиск: ${state.search.trim()}`;
  if(state.categoryCode!=='all')return categoryLabel(state.categoryCode);
  if(state.categoryMain!=='all')return CATEGORY_TREE.find(main=>main.id===state.categoryMain)?.label||'Все товары';
  return'Все товары';
}
function primaryCategoryCode(product){if(state.categoryCode!=='all'&&categoryCodes(product).includes(state.categoryCode))return state.categoryCode;const main=state.categoryMain!=='all'?CATEGORY_TREE.find(item=>item.id===state.categoryMain):null;return categoryCodes(product).find(code=>main?.codes.includes(code))||categoryCodes(product)[0]||'13'}
function categoryTrail(product){const code=primaryCategoryCode(product),entry=CATEGORY_BY_CODE.get(code);return entry?{code,main:entry.main,label:entry.label}:{code:'13',main:CATEGORY_TREE[0],label:'Декор и аксессуары'}}
function productCategoryButton(product){const primary=primaryCategoryCode(product),codes=[primary,...categoryCodes(product)].filter((code,index,items)=>CATEGORY_BY_CODE.has(code)&&items.indexOf(code)===index);const visible=codes.length?codes:[categoryTrail(product).code];return`<div class="product-categories" aria-label="Категории товара">${visible.map(code=>{const entry=CATEGORY_BY_CODE.get(code),target=entry.main.children.length?`data-category-code="${escapeAttr(code)}"`:`data-main-category="${escapeAttr(entry.main.id)}"`;return`<button class="product-type product-category-link" type="button" ${target} aria-label="Показать категорию «${escapeAttr(categoryLabel(code))}»">${escapeHtml(categoryLabel(code))}</button>`}).join('')}</div>`}
function detailCategoryTemplate(product){const trail=categoryTrail(product);return`<nav class="detail-breadcrumbs" aria-label="Категории товара"><button type="button" data-main-category="${escapeAttr(trail.main.id)}">${escapeHtml(trail.main.label)}</button>${trail.main.children.length?`<span aria-hidden="true">›</span><button type="button" data-category-code="${escapeAttr(trail.code)}">${escapeHtml(trail.label)}</button>`:''}</nav>`}

const COMPUTER_CHAIR_CATEGORY='Компьютерные кресла',COMPUTER_CHAIR_LABEL='Компьютерное кресло',BEDROOM_CATEGORY='Кровати и мебель для спальни',RATTAN_CATEGORY='Ротанг',OUTDOOR_FURNITURE_CATEGORY='Садовая мебель, ковка',OUTDOOR_FURNITURE_TERMS='уличная мебель садовая мебель дачная мебель мебель для террас мебель для кафе кованая мебель ковка',RATTAN_TERMS='ротанг мебель из ротанга';
const CONSTRUCTION_MARKERS=[
  {key:'swivel-360',label:'поворотная опора 360°',pattern:/опора\s*360(?:\s*°)?/i},
  {key:'swivel',label:'поворотная основа',pattern:/(?:поворотн|вращающ)[а-яё]*/i},
  {key:'runners',label:'опора-полозья',pattern:/полоз[а-яё]*/i},
  {key:'casters',label:'на колёсах',pattern:/(?:колес|крестовин|газлифт)[а-яё]*/i},
  {key:'armrests',label:'с подлокотниками',pattern:/с\s+подлокотник[а-яё]*/i},
  {key:'no-armrests',label:'без подлокотников',pattern:/без\s+подлокотник[а-яё]*/i},
  {key:'folding',label:'складная конструкция',pattern:/(?:раскладн|складн)[а-яё]*/i}
];
function constructionDescriptor(product){const text=[product.name,...(product.variants||[]).map(v=>`${v.specs||''} ${v.label||''}`)].join(' ').toLocaleLowerCase('ru-RU'),markers=CONSTRUCTION_MARKERS.filter(marker=>marker.pattern.test(text));return{key:markers.map(marker=>marker.key).join('|')||'standard',label:markers.map(marker=>marker.label).join(' · ')}}
const isComputerChair=product=>/^кресла\s+tetchair(?:\s|$)/i.test(product.collection||'');
function outdoorCatalogText(product){return[product.name,product.category,product.collection,product.searchText,...(product.variants||[]).flatMap(variant=>[variant.label,variant.specs])].filter(Boolean).join(' ')}
function isRattanFurniture(product){const text=outdoorCatalogText(product);return product.category===RATTAN_CATEGORY||/(?:^|[^а-яё])ротанг[а-яё]*(?:$|[^а-яё])/iu.test(text)}
function isForgedOutdoorFurniture(product){const text=outdoorCatalogText(product);return/(?:^|[^а-яё])ковк[а-яё]*(?:$|[^а-яё])/iu.test(text)}
function enrichCatalogProduct(product){
  const computerChair=isComputerChair(product),bedroom=product.category==='Спальня',rattan=isRattanFurniture(product),outdoor=isForgedOutdoorFurniture(product),construction=constructionDescriptor(product);
  const searchTerms=[computerChair?'компьютерное кресло компьютерные кресла офисное кресло офисные кресла':'',rattan?RATTAN_TERMS:'',outdoor?OUTDOOR_FURNITURE_TERMS:''].filter(Boolean).join(' ');
  const assignedCodes=[...new Set((product.variants||[]).flatMap(variant=>state.categoryAssignments[String(variant.sourceId)]||[]))];
  const codes=categoryCodes(product).length?categoryCodes(product):assignedCodes.length?assignedCodes:computerChair?['12']:bedroom?['11']:rattan?['10']:outdoor?['9']:['13'];
  return {...product,categoryCodes:codes,category:categoryLabel(codes[0])||product.category,constructionKey:construction.key,kindLabel:categoryLabel(codes[0]),searchTerms};
}
function normalizeCatalogProducts(products){
  return products.map((product,index)=>{
    const variants=product.variants||[];
    return enrichCatalogProduct({...product,name:stripPackaging(product.name),variants,variantCount:variants.length,_index:index,_selected:variants[0]?.sourceId});
  });
}
async function init(){try{const[indexResponse,categoryResponse]=await Promise.all([fetch(DATA_BASE+'catalog-index.json',{cache:'no-cache'}),fetch(DATA_BASE+'category-assignments.json',{cache:'no-cache'})]);if(!indexResponse.ok||!categoryResponse.ok)throw Error(`HTTP ${indexResponse.status}/${categoryResponse.status}`);const[d,categories]=await Promise.all([indexResponse.json(),categoryResponse.json()]);state.categoryAssignments=categories.assignments||{};state.products=normalizeCatalogProducts(d.products);window.auditVariantPresentation?.(state.products);restoreSharedState();expandedMobileCategory=state.categoryMain==='all'?null:state.categoryMain;renderCategories();applyFilters();updateCounters();renderRecent();$('#searchForm')?.addEventListener('submit',submitSearch);const q=hashParams(),snapshot=catalogSnapshot();if(q.get('product'))await openProduct(q.get('product'),q.get('variant'),{historyMode:'direct'});else history.replaceState({view:'catalog',catalog:snapshot,scrollY:scrollY},'',catalogUrl(snapshot));if(q.get('view')==='cart'&&Object.keys(state.cart).length){renderCart();els.cartDialog.showModal();document.body.style.overflow='hidden'}}catch(e){console.error('[catalog-index]',e);els.count.hidden=false;els.count.textContent='Каталог временно недоступен';els.empty.hidden=false}}
function restoreSharedState(){const q=hashParams();if(CATEGORY_TREE.some(item=>item.id===q.get('main')))state.categoryMain=q.get('main');if(CATEGORY_BY_CODE.has(q.get('category'))){const main=categoryMainFor(q.get('category'));state.categoryMain=main.id;state.categoryCode=main.children.length?q.get('category'):'all'}state.page=Math.max(1,Number(q.get('page'))||1);state.search=q.get('q')||'';state.sort=['featured','price-asc','price-desc','name'].includes(q.get('sort'))?q.get('sort'):'featured';$('#searchInput').value=state.search;$('#sortSelect').value=state.sort;if(q.get('favorites')){state.favorites=q.get('favorites').split('~').filter(id=>state.products.some(p=>p.id===id));storage.write('forma:favorites',state.favorites);state.view='favorites'}if(q.get('cart')){const cart={};q.get('cart').split('~').forEach(x=>{const[id,qty]=x.split('.');if(/^\d+$/.test(id))cart[id]=Math.max(1,Number(qty)||1)});if(Object.keys(cart).length){state.cart=cart;storage.write('forma:cart',cart)}}}
function variantCategoryCodes(product,variant){const assigned=(state.categoryAssignments[String(variant.sourceId)]||[]).map(String);return assigned.length?assigned:categoryCodes(product)}
function categoryVariantCount(codes=null){return state.products.reduce((count,product)=>count+(product.variants||[]).reduce((sum,variant)=>sum+(!codes||variantCategoryCodes(product,variant).some(code=>codes.includes(code))?1:0),0),0)}
function renderCategories(){
  const primary=`<div class="category-primary" role="group" aria-label="Основные категории"><button class="category-main ${state.categoryMain==='all'?'active':''}" data-main-category="all"><span class="category-icon" aria-hidden="true">∞</span><span data-mobile-label="${MOBILE_CATEGORY_LABELS.all}">Все товары</span><small>${categoryVariantCount()}</small></button>${CATEGORY_TREE.map(main=>`<button class="category-main ${state.categoryMain===main.id?'active':''}" data-main-category="${main.id}"><span class="category-icon" aria-hidden="true">${main.icon}</span><span data-mobile-label="${escapeAttr(MOBILE_CATEGORY_LABELS[main.id])}">${escapeHtml(main.label)}</span><small>${categoryVariantCount(main.codes)}</small></button>`).join('')}</div>`;
  const subgroups=CATEGORY_TREE.filter(main=>main.children.length).map(main=>`<section class="category-subgroup ${state.categoryMain===main.id?'active':''}" aria-labelledby="category-${main.id}"><h3 id="category-${main.id}">${escapeHtml(main.label)}</h3><div>${main.children.map(([code,label])=>`<button class="category-chip ${state.categoryCode===code?'active':''}" data-category-code="${code}">${escapeHtml(label)} <span>${categoryVariantCount([code])}</span></button>`).join('')}<button class="category-chip category-all ${state.categoryMain===main.id&&state.categoryCode==='all'?'active':''}" data-main-category="${main.id}" aria-label="Показать всю категорию «${escapeAttr(main.label)}»">Все <span>${categoryVariantCount(main.codes)}</span></button></div></section>`).join('');
  const mobileSections=CATEGORY_TREE.map(main=>{const open=expandedMobileCategory===main.id,selected=state.categoryMain===main.id,panelId=`mobile-category-${main.id}`;const options=`<button class="mobile-category-option mobile-category-all ${selected&&state.categoryCode==='all'?'active':''}" data-main-category="${main.id}"${selected&&state.categoryCode==='all'?' aria-current="true"':''}><span>${escapeHtml(MOBILE_ALL_LABELS[main.id])}</span><small>${categoryVariantCount(main.codes)}</small><i aria-hidden="true">›</i></button>${main.children.map(([code,label])=>`<button class="mobile-category-option ${state.categoryCode===code?'active':''}" data-category-code="${code}"${state.categoryCode===code?' aria-current="true"':''}><span>${escapeHtml(label)}</span><small>${categoryVariantCount([code])}</small><i aria-hidden="true">›</i></button>`).join('')}`;return`<section class="mobile-category-section ${open?'open':''} ${selected?'selected':''}"><button class="mobile-category-trigger" type="button" data-mobile-category-toggle="${main.id}" aria-expanded="${open}" aria-controls="${panelId}"><span class="mobile-category-icon" aria-hidden="true">${main.icon}</span><span class="mobile-category-name">${escapeHtml(MOBILE_CATEGORY_LABELS[main.id])}</span><small>${categoryVariantCount(main.codes)}</small><span class="mobile-category-chevron" aria-hidden="true">⌄</span></button><div class="mobile-category-panel" id="${panelId}"${open?'':' hidden'}>${main.children.length>5?'<p class="mobile-category-hint"><span aria-hidden="true">↕</span> Листайте подкатегории</p>':''}${options}</div></section>`}).join('');
  const mobile=`<div class="mobile-category-shell ${expandedMobileCategory?'has-open':''}"><button class="mobile-scroll-button mobile-scroll-up" type="button" data-mobile-category-scroll="-1" aria-label="Прокрутить категории вверх">⌃</button><div class="mobile-category-accordion" aria-label="Категории каталога">${mobileSections}</div><button class="mobile-scroll-button mobile-scroll-down" type="button" data-mobile-category-scroll="1" aria-label="Прокрутить категории вниз">⌄</button></div>`;
  els.categories.innerHTML=primary+`<div class="category-subgroups">${subgroups}</div>`+mobile;
  bindMobileCategoryScroller();
}
function bindMobileCategoryScroller(){const shell=$('.mobile-category-shell',els.categories),scroller=$('.mobile-category-accordion',els.categories);if(!shell||!scroller)return;const sync=()=>{const max=Math.max(0,scroller.scrollHeight-scroller.clientHeight);shell.classList.toggle('can-scroll-up',scroller.scrollTop>4);shell.classList.toggle('can-scroll-down',scroller.scrollTop<max-4)};scroller.addEventListener('scroll',sync,{passive:true});requestAnimationFrame(()=>{const open=$('.mobile-category-section.open',scroller);if(open&&open.offsetTop>scroller.clientHeight*.55)scroller.scrollTop=Math.max(0,open.offsetTop-4);sync()})}
function normalizeSearch(value=''){return String(value).toLocaleLowerCase('ru-RU').replace(/ё/g,'е').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zа-я0-9]+/giu,' ').trim()}
function searchRelevance(product,query){const needle=normalizeSearch(query);if(!needle)return 0;if(/^\d+$/.test(needle)){const ids=(product.variants||[]).map(variant=>String(variant.sourceId||''));if(ids.includes(needle))return 0;const prefix=ids.findIndex(id=>id.startsWith(needle));if(prefix>=0)return 10+prefix;const partial=ids.findIndex(id=>id.includes(needle));return partial>=0?50+partial:Number.POSITIVE_INFINITY}const name=normalizeSearch(product.name),index=name.indexOf(needle);if(index<0)return Number.POSITIVE_INFINITY;const words=name.split(' '),exactWord=words.indexOf(needle),prefixWord=words.findIndex(word=>word.startsWith(needle));if(name===needle)return 0;if(exactWord>=0)return 10+exactWord;if(prefixWord>=0)return 20+prefixWord;return 100+index}
function searchMatches(product,query){return Number.isFinite(searchRelevance(product,query))}
function matchesSelectedCategory(product){const codes=categoryCodes(product);if(state.categoryCode!=='all')return codes.includes(state.categoryCode);if(state.categoryMain!=='all'){const main=CATEGORY_TREE.find(item=>item.id===state.categoryMain);return main?codes.some(code=>main.codes.includes(code)):true}return true}
function applyFilters(){const q=state.search.trim();if(q&&(state.categoryMain!=='all'||state.categoryCode!=='all')){state.categoryMain='all';state.categoryCode='all';expandedMobileCategory=null;renderCategories()}state.filtered=state.products.filter(p=>(state.view!=='favorites'||state.favorites.includes(p.id))&&matchesSelectedCategory(p)&&searchMatches(p,q)&&(!state.min||minPrice(p)>=Number(state.min))&&(!state.max||minPrice(p)<=Number(state.max))&&(!state.multi||p.variants.length>1));state.filtered.sort((a,b)=>{if(q){const relevance=searchRelevance(a,q)-searchRelevance(b,q);if(relevance)return relevance}return state.sort==='price-asc'?minPrice(a)-minPrice(b):state.sort==='price-desc'?minPrice(b)-minPrice(a):state.sort==='name'?a.name.localeCompare(b.name,'ru'):a._index-b._index});state.page=Math.min(state.page,Math.max(1,Math.ceil(state.filtered.length/PAGE_SIZE)));renderCatalog()}
function submitSearch(event){event?.preventDefault();const input=$('#searchInput');state.search=input.value;state.page=1;applyFilters();syncCatalogHistory();requestAnimationFrame(()=>instantScroll(els.grid))}
function renderCatalog(){const list=state.filtered.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE),showFavorites=state.view==='favorites';els.title.textContent=currentCatalogTitle();els.count.hidden=false;els.count.textContent=`${state.filtered.length} ${plural(state.filtered.length,'модель','модели','моделей')}`;els.favoritesToolbar.hidden=!showFavorites;els.shareFavorites.hidden=!showFavorites||!state.favorites.length;els.grid.innerHTML=list.map(cardTemplate).join('');els.empty.hidden=!!list.length;renderPagination()}
function renderPagination(){const total=Math.ceil(state.filtered.length/PAGE_SIZE);if(total<=1){els.pages.innerHTML='';return}const pages=[];for(let i=1;i<=total;i++)if(i===1||i===total||Math.abs(i-state.page)<=1)pages.push(i);let prev=0;const pageButtons=pages.map(i=>`${i-prev>1?'<span class="pagination-gap" aria-hidden="true">…</span>':''}<button class="page-button ${i===state.page?'active':''}" data-page="${i}"${i===state.page?' aria-current="page"':''}>${i}</button>${(prev=i)&&''}`).join('');const previous=state.page>1?`data-page="${state.page-1}"`:"disabled";const next=state.page<total?`data-page="${state.page+1}"`:"disabled";els.pages.innerHTML=`<button class="page-button page-arrow" ${previous} aria-label="Предыдущая страница"><span aria-hidden="true">‹</span></button>${pageButtons}<button class="page-button page-arrow" ${next} aria-label="Следующая страница"><span aria-hidden="true">›</span></button>`}

function catalogSnapshot(){return{categoryMain:state.categoryMain,categoryCode:state.categoryCode,search:state.search,sort:state.sort,page:state.page,min:state.min,max:state.max,multi:state.multi,view:state.view}}
function catalogUrl(snapshot=catalogSnapshot()){const params=new URLSearchParams;if(snapshot.categoryCode!=='all')params.set('category',snapshot.categoryCode);else if(snapshot.categoryMain!=='all')params.set('main',snapshot.categoryMain);if(snapshot.page>1)params.set('page',String(snapshot.page));if(snapshot.search)params.set('q',snapshot.search);if(snapshot.sort!=='featured')params.set('sort',snapshot.sort);return baseUrl()+(params.size?`#${params}`:'#catalog')}
function productUrl(id,sourceId){const params=new URLSearchParams({product:id});if(sourceId)params.set('variant',String(sourceId));return`${baseUrl()}#${params}`}
function syncCatalogHistory(){if(history.state?.view==='product'&&els.productDialog.open)return;const snapshot=catalogSnapshot();history.replaceState({view:'catalog',catalog:snapshot,scrollY},'',catalogUrl(snapshot))}
function instantScroll(target){const root=document.documentElement,previous=root.style.scrollBehavior;root.style.scrollBehavior='auto';if(typeof target==='number')scrollTo(0,target);else (target?.id==='catalog'?els.grid:target)?.scrollIntoView({block:'start'});requestAnimationFrame(()=>{root.style.scrollBehavior=previous})}
function restoreCatalog(snapshot={},y=0){Object.assign(state,{categoryMain:'all',categoryCode:'all',search:'',sort:'featured',page:1,min:'',max:'',multi:false,view:'catalog'},snapshot);expandedMobileCategory=state.categoryMain==='all'?null:state.categoryMain;$('#searchInput').value=state.search;$('#sortSelect').value=state.sort;$('#priceMin').value=state.min;$('#priceMax').value=state.max;$('#multiVariant').checked=state.multi;renderCategories();applyFilters();requestAnimationFrame(()=>instantScroll(Number(y)||0))}
async function getFullProduct(p){if(state.detailCache.has(p.id))return{...state.detailCache.get(p.id),name:p.name,constructionKey:p.constructionKey,categoryCodes:p.categoryCodes};const r=await fetch(DATA_BASE+p.detailShard);if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();Object.values(d.products).forEach(x=>state.detailCache.set(x.id,enrichCatalogProduct(x)));const full=state.detailCache.get(p.id)||p;return{...full,name:p.name,constructionKey:p.constructionKey,categoryCodes:p.categoryCodes}}
async function openProduct(id,sourceId,{historyMode='push'}={}){const s=state.products.find(p=>p.id===id);if(!s)return;const snapshot=catalogSnapshot(),returnScrollY=scrollY;els.productDialog.dataset.returnScrollY=String(returnScrollY);if(historyMode==='push'){history.replaceState({view:'catalog',catalog:snapshot,scrollY:returnScrollY},'',catalogUrl(snapshot));history.pushState({view:'product',productId:id,sourceId:sourceId||s._selected,catalog:snapshot,returnScrollY,openedFromCatalog:true},'',productUrl(id,sourceId||s._selected))}else if(historyMode==='direct'){history.replaceState({view:'product',productId:id,sourceId:sourceId||s._selected,catalog:snapshot,returnScrollY,openedFromCatalog:false},'',productUrl(id,sourceId||s._selected))}if(!state.recent.includes(id)){state.recent.unshift(id);state.recent=state.recent.slice(0,8);storage.write('forma:recent',state.recent)}els.detail.innerHTML='<div class="detail-loading">Загружаем фотографии…</div>';if(!els.productDialog.open)els.productDialog.showModal();document.body.style.overflow='hidden';try{const p=await getFullProduct(s);p._selected=sourceId||s._selected;els.detail.innerHTML=detailTemplate(p,currentVariant(p,p._selected));renderRecent()}catch{els.detail.innerHTML='<div class="detail-loading">Не удалось загрузить карточку.</div>'}}
async function selectVariant(id,sourceId){const s=state.products.find(p=>p.id===id);s._selected=sourceId;const p=await getFullProduct(s);p._selected=sourceId;els.detail.innerHTML=detailTemplate(p,currentVariant(p,sourceId));if(history.state?.view==='product')history.replaceState({...history.state,sourceId},'',productUrl(id,sourceId))}
function closeProduct(){const current=history.state;if(current?.view==='product'&&current.openedFromCatalog){history.back();return}if(els.productDialog.open)closeDialog(els.productDialog);const snapshot=current?.catalog||catalogSnapshot();history.replaceState({view:'catalog',catalog:snapshot,scrollY},'',catalogUrl(snapshot))}
function closeDialog(d){d.close();document.body.style.overflow=''}
function addToCart(id,sourceId){const p=state.products.find(x=>x.id===id);if(!p)return;const v=currentVariant(p,sourceId||p._selected),k=String(v.sourceId);state.cart[k]=(state.cart[k]||0)+1;storage.write('forma:cart',state.cart);updateCounters();toast('Добавили в корзину')}
function updateCounters(){const favorites=state.favorites.length,cart=Object.values(state.cart).reduce((a,b)=>a+b,0);$('#favoritesCount').textContent=favorites;$('#cartCount').textContent=cart;$('#favoritesButton').setAttribute('aria-label',`Избранное: ${favorites} ${plural(favorites,'товар','товара','товаров')}`);$('#cartButton').setAttribute('aria-label',`Корзина: ${cart} ${plural(cart,'товар','товара','товаров')}`)}
function syncFavoriteButtons(id=null){document.querySelectorAll('[data-favorite]').forEach(button=>{if(id!==null&&String(button.dataset.favorite)!==String(id))return;const active=state.favorites.includes(button.dataset.favorite);button.classList.toggle('active',active);button.setAttribute('aria-label',active?'Убрать из избранного':'Добавить в избранное');button.textContent=active?'♥':'♡'})}
function toggleFavorite(id){const active=!state.favorites.includes(id);state.favorites=active?[...state.favorites,id]:state.favorites.filter(x=>x!==id);storage.write('forma:favorites',state.favorites);updateCounters();if(state.view==='favorites')applyFilters();else syncFavoriteButtons(id);renderRecent();syncFavoriteButtons();toast(active?'Добавили в избранное':'Убрали из избранного')}
function cartRows(){const map=new Map(state.products.flatMap(p=>p.variants.map(v=>[String(v.sourceId),{product:p,variant:v}])));return Object.entries(state.cart).map(([key,qty])=>({...map.get(key),key,qty})).filter(x=>x.variant)}
function orderText(rows=cartRows(),total=rows.reduce((s,x)=>s+x.variant.wholesalePrice*x.qty,0)){return`Здравствуйте! Хочу оформить заказ в FORMA HOME:\n${rows.map(x=>`• ${stripModel(x.product.name)} — ${variantLabel(x.variant)}, арт. ${x.variant.sourceId}, ${x.qty} шт.`).join('\n')}\nИтого: ${money(total)}\n\nОкончательное наличие и срок отгрузки подтвердит менеджер после получения заявки.`}
const cartShareUrl=()=>`${baseUrl()}#view=cart&cart=${Object.entries(state.cart).map(([id,q])=>`${id}.${q}`).join('~')}`,favoritesShareUrl=()=>`${baseUrl()}#view=favorites&favorites=${state.favorites.join('~')}`;
function renderCart(){const rows=cartRows();els.cartItems.innerHTML=rows.length?`<div class="cart-list">${rows.map(({product:p,variant:v,key,qty})=>`<article class="cart-item" data-open="${escapeAttr(p.id)}" data-source="${v.sourceId}"><img src="${escapeAttr(imageUrl(v.primaryImage))}" alt=""><div><h3>${escapeHtml(stripModel(p.name))}</h3><p>${escapeHtml(variantLabel(v))}<br>арт. ${v.sourceId}</p><div class="qty"><button data-qty="${key}" data-delta="-1">−</button><span>${qty}</span><button data-qty="${key}" data-delta="1">+</button></div></div><div><strong>${money(v.wholesalePrice*qty)}</strong><button class="remove" data-remove="${key}">Удалить</button></div></article>`).join('')}</div>`:'<div class="cart-empty"><h3>Корзина пока пуста</h3></div>';const total=rows.reduce((s,x)=>s+x.variant.wholesalePrice*x.qty,0),share=cartShareUrl(),order=orderText(rows,total),msg=encodeURIComponent(order+'\n'+share),mailSubject=encodeURIComponent('Заказ FORMA HOME'),mailBody=encodeURIComponent(order+'\n\nСсылка на собранную корзину:\n'+share);els.cartFooter.innerHTML=rows.length?`<div class="cart-total"><span>Итого</span><span>${money(total)}</span></div><p class="availability-note">Окончательное наличие и срок отгрузки подтвердит менеджер после получения заявки.</p><div class="checkout-actions"><a class="primary-button" href="https://wa.me/?text=${msg}" target="_blank" rel="noopener">Заказать в WhatsApp</a><a class="messenger-button" href="https://t.me/share/url?url=${encodeURIComponent(share)}&text=${encodeURIComponent(order)}" target="_blank" rel="noopener">Заказать в Telegram</a><a class="messenger-button" href="mailto:${ORDER_EMAIL}?subject=${mailSubject}&body=${mailBody}">Заказать по e-mail</a><button class="share-button" data-share-cart>Поделиться корзиной</button></div>`:''}
async function sharePayload(title,text,url){if(navigator.share){try{await navigator.share({title,text,url})}catch{}}else{await navigator.clipboard?.writeText(url);toast('Ссылка скопирована')}}
function recentCardTemplate(p){const v=currentVariant(p,p._selected),favorite=state.favorites.includes(p.id),retail=Number(v.retailPrice)>Number(v.wholesalePrice);return`<article class="recent-card"><button class="recent-image" data-open="${escapeAttr(p.id)}" aria-label="Открыть ${escapeAttr(stripModel(p.name))}"><img src="${escapeAttr(imageUrl(v.primaryImage))}" alt="${escapeAttr(stripModel(p.name))}" loading="lazy" onerror="this.remove()"></button><div class="recent-info"><button class="recent-favorite ${favorite?'active':''}" data-favorite="${escapeAttr(p.id)}" aria-label="${favorite?'Убрать из избранного':'Добавить в избранное'}"></button><button class="recent-name" data-open="${escapeAttr(p.id)}">${escapeHtml(stripModel(p.name))}</button><p class="recent-variant">${escapeHtml(variantLabel(v))}</p><div class="recent-bottom"><span class="recent-prices"><strong>${money(v.wholesalePrice)}</strong>${retail?`<del>${money(v.retailPrice)}</del>`:''}</span><button class="recent-add" data-add="${escapeAttr(p.id)}" data-source="${v.sourceId}">В корзину</button></div></div></article>`}
function renderRecent(){const p=state.recent.map(id=>state.products.find(x=>x.id===id)).filter(Boolean).slice(0,5);$('#recentSection').hidden=!p.length;$('#recentRow').innerHTML=p.map(recentCardTemplate).join('')}
function resetFilters(){state.view='catalog';state.categoryMain='all';state.categoryCode='all';state.search='';state.min='';state.max='';state.multi=false;state.page=1;expandedMobileCategory=null;$('#searchInput').value='';$('#priceMin').value='';$('#priceMax').value='';$('#multiVariant').checked=false;renderCategories();applyFilters();syncCatalogHistory()}function toast(m){els.toast.textContent=m;els.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>els.toast.classList.remove('show'),1800)}

document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-open]');if(!b)return;if(b.dataset.mobileCategoryToggle!==undefined){expandedMobileCategory=expandedMobileCategory===b.dataset.mobileCategoryToggle?null:b.dataset.mobileCategoryToggle;renderCategories();return}if(b.dataset.mobileCategoryScroll!==undefined){const scroller=$('.mobile-category-accordion',els.categories);if(scroller)scroller.scrollBy({top:Number(b.dataset.mobileCategoryScroll)*Math.max(160,scroller.clientHeight*.72),behavior:'smooth'});return}if(b.dataset.mainCategory!==undefined||b.dataset.categoryCode!==undefined){if(b.dataset.categoryCode!==undefined){state.categoryCode=b.dataset.categoryCode;state.categoryMain=categoryMainFor(state.categoryCode)?.id||'all'}else{state.categoryMain=b.dataset.mainCategory;state.categoryCode='all'}expandedMobileCategory=state.categoryMain==='all'?null:state.categoryMain;state.search='';$('#searchInput').value='';state.view='catalog';state.page=1;if(els.productDialog.open)closeDialog(els.productDialog);renderCategories();applyFilters();syncCatalogHistory();requestAnimationFrame(()=>instantScroll($('#catalog')));return}if(b.dataset.page){state.page=Number(b.dataset.page);renderCatalog();syncCatalogHistory();instantScroll($('#catalog'))}if(b.dataset.favorite){e.preventDefault();e.stopPropagation();toggleFavorite(b.dataset.favorite);return}if(b.dataset.add){e.preventDefault();e.stopPropagation();addToCart(b.dataset.add,b.dataset.source);return}if(b.dataset.open){if(els.cartDialog.open)closeDialog(els.cartDialog);await openProduct(b.dataset.open,b.dataset.source)}if(b.dataset.cardVariant){e.stopPropagation();const p=state.products.find(x=>x.id===b.dataset.product);if(p){p._selected=b.dataset.cardVariant;renderCatalog()}}if(b.dataset.variant)await selectVariant(b.closest('[data-detail-id]').dataset.detailId,b.dataset.variant);if(b.dataset.image){$('#galleryMain').src=b.dataset.image;document.querySelectorAll('.thumbnail').forEach(x=>x.classList.toggle('active',x===b))}if(b.hasAttribute('data-close-dialog'))closeProduct();if(b.hasAttribute('data-close-cart'))closeDialog(els.cartDialog);if(b.dataset.qty){state.cart[b.dataset.qty]=(state.cart[b.dataset.qty]||0)+Number(b.dataset.delta);if(state.cart[b.dataset.qty]<=0)delete state.cart[b.dataset.qty];storage.write('forma:cart',state.cart);updateCounters();renderCart()}if(b.dataset.remove){delete state.cart[b.dataset.remove];storage.write('forma:cart',state.cart);updateCounters();renderCart()}if(b.dataset.shareProduct!==undefined){const p=state.products.find(x=>x.id===b.dataset.shareProduct);await sharePayload(stripModel(p.name),variantLabel(currentVariant(p,b.dataset.source)),productUrl(p.id,b.dataset.source))}if(b.hasAttribute('data-share-cart'))await sharePayload('Корзина FORMA HOME',orderText(),cartShareUrl())});
$('#searchInput').addEventListener('input',e=>{state.search=e.target.value;state.page=1;applyFilters();syncCatalogHistory()});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;applyFilters();syncCatalogHistory()});['priceMin','priceMax'].forEach(id=>$('#'+id).addEventListener('input',e=>{state[id==='priceMin'?'min':'max']=e.target.value.replace(/\D/g,'');state.page=1;applyFilters();syncCatalogHistory()}));$('#multiVariant').addEventListener('change',e=>{state.multi=e.target.checked;state.page=1;applyFilters();syncCatalogHistory()});$('#filterToggle').addEventListener('click',e=>{const o=$('#filters').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',o)});$('#clearFilters').addEventListener('click',resetFilters);$('#emptyReset').addEventListener('click',resetFilters);$('#cartButton').addEventListener('click',()=>{renderCart();els.cartDialog.showModal();document.body.style.overflow='hidden'});$('#favoritesButton').addEventListener('click',()=>{state.view='favorites';state.categoryMain='all';state.categoryCode='all';state.page=1;expandedMobileCategory=null;renderCategories();applyFilters();syncCatalogHistory();instantScroll($('#catalog'))});els.shareFavorites.addEventListener('click',()=>sharePayload('Избранное FORMA HOME','Моя подборка мебели',favoritesShareUrl()));els.productDialog.addEventListener('click',e=>{if(e.target===els.productDialog)closeProduct()});els.productDialog.addEventListener('cancel',e=>{e.preventDefault();closeProduct()});els.cartDialog.addEventListener('click',e=>{if(e.target===els.cartDialog)closeDialog(els.cartDialog)});window.addEventListener('popstate',event=>{const entry=event.state;if(entry?.view==='product'){openProduct(entry.productId,entry.sourceId,{historyMode:'pop'});return}if(els.productDialog.open)closeDialog(els.productDialog);restoreCatalog(entry?.catalog||{},entry?.scrollY||0)});init();
