const DATA_BASE='./data/',ASSET_BASE='https://gkkm8bm7rn-eng.github.io/tetopt/',ORDER_PHONE='79057267946',ORDER_EMAIL='postes@mail.ru',PAGE_SIZE=24;
const storage={read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const state={products:[],filtered:[],categoryAssignments:{},categoryMain:'all',categoryCode:'all',search:'',sort:'featured',page:1,min:'',max:'',multi:false,view:'catalog',favorites:storage.read('forma:favorites',[]),cart:storage.read('forma:cart',{}),recent:storage.read('forma:recent',[]),detailCache:new Map()};
const $=(s,r=document)=>r.querySelector(s),els={grid:$('#productGrid'),count:$('#resultCount'),title:$('#catalogTitle'),categories:$('#categoryRow'),pages:$('#pagination'),empty:$('#emptyState'),detail:$('#productDetail'),productDialog:$('#productDialog'),cartDialog:$('#cartDialog'),cartItems:$('#cartItems'),cartFooter:$('#cartFooter'),toast:$('#toast'),favoritesToolbar:$('#favoritesToolbar'),shareFavorites:$('#shareFavorites')};
const stripPackaging=(n='')=>String(n).replace(/\(\s*\d+\s*(?:шт\.?|штук)\s*(?:в\s*(?:\d+\s*(?:[-–—]\s*х)?\s*)?)?(?:упаковк[а-яёa-z]*|уп\.?)\s*\)/giu,' ').replace(/,\s*\d+\s*(?:шт\.?|штук)\s*(?:в\s*(?:\d+\s*(?:[-–—]\s*х)?\s*)?)?(?:упаковк[а-яёa-z]*|уп\.?)\s*\)/giu,')').replace(/(?:\s*[\[(/,-]?\s*)\d+\s*(?:шт\.?|штук)\s*(?:в\s*(?:\d+\s*(?:[-–—]\s*х)?\s*)?)?(?:упаковк[а-яёa-z]*|уп\.?)/giu,' ').replace(/\s+/g,' ').trim();
const money=v=>new Intl.NumberFormat('ru-RU').format(Number(v)||0)+' ₽',imageUrl=p=>!p?'':/^https?:/.test(p)?p:ASSET_BASE+String(p).replace(/^\//,''),stripModel=(n='')=>stripPackaging(n).replace(/\s*\(мод\.[^)]+\)\s*/gi,' ').replace(/\s+/g,' ').trim();
const currentVariant=(p,id)=>p.variants.find(v=>String(v.sourceId)===String(id))||p.variants[0],minPrice=p=>Math.min(...p.variants.map(v=>Number(v.wholesalePrice)||Infinity));
const variantLabel=v=>v.label||(v.specs||'').split(',').map(s=>s.trim()).filter(Boolean).slice(-2).join(' · ')||`Вариант ${v.sourceId}`;
function sleepingSize(product,variant){
  if(!/^\s*кровать(?:\s|$)/i.test(product.name||''))return'';
  const match=`${variant.specs||''} ${variant.label||''}`.match(/(\d{2,3}(?:[.,]\d+)?\s*[хx×]\s*\d{2,3}(?:[.,]\d+)?)\s*см/i);
  return match?match[1].replace(/\s*[хx×]\s*/i,' × ').replace(/\s+/g,' ').trim()+' см':'';
}
const plural=(n,a,b,c)=>n%100>=11&&n%100<=14?c:n%10===1?a:n%10>=2&&n%10<=4?b:c,escapeHtml=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),escapeAttr=escapeHtml;
const hashParams=()=>new URLSearchParams(location.hash.replace(/^#/,'')),baseUrl=()=>location.href.split('#')[0];
const directContactUrl=(channel,text)=>{const encoded=encodeURIComponent(text);return channel==='whatsapp'?`https://wa.me/${ORDER_PHONE}?text=${encoded}`:channel==='telegram'?`https://t.me/+${ORDER_PHONE}?text=${encoded}`:''};
if('scrollRestoration'in history)history.scrollRestoration='manual';

const CATEGORY_TREE=[
  {id:'interior',label:'Интерьерная мебель',icon:'⌂',codes:['1','2','14','15','16','7','8','5','3','6','11','4','13'],children:[['1','Стулья'],['2','Барные и полубарные стулья'],['14','Обеденные столы'],['15','Журнальные и кофейные столы'],['16','Письменные столы'],['7','Комоды и тумбы'],['8','Шкафы и стеллажи'],['5','Диваны'],['3','Кресла'],['6','Модульная мягкая мебель'],['11','Кровати'],['4','Пуфы, банкетки и табуреты'],['13','Декор и аксессуары']]},
  {id:'outdoor',label:'Садовая мебель',icon:'♧',codes:['9','10'],children:[['9','Мебель из металла'],['10','Мебель из ротанга']]},
  {id:'horeca',label:'Мебель для HoReCa',icon:'▦',codes:['18'],children:[]},
  {id:'office',label:'Офисные кресла',icon:'◒',codes:['12'],children:[]}
];
const MOBILE_CATEGORY_LABELS={all:'Все',interior:'Интерьер',outdoor:'Сад',horeca:'HoReCa',office:'Офисные кресла'};
const MOBILE_ALL_LABELS={interior:'Вся интерьерная мебель',outdoor:'Вся садовая мебель',horeca:'Вся мебель для HoReCa',office:'Все офисные кресла'};
let expandedMobileCategory=null;
const CATEGORY_BY_CODE=new Map(CATEGORY_TREE.flatMap(main=>main.codes.map(code=>[code,{main,label:main.children.find(child=>child[0]===code)?.[1]||main.label}])));
const categoryCodes=product=>(product.categoryCodes||[]).map(String);
const categoryMainFor=code=>CATEGORY_BY_CODE.get(String(code))?.main;
const categoryLabel=code=>CATEGORY_BY_CODE.get(String(code))?.label||'';
function currentCatalogTitle(){
  if(state.view==='favorites')return'Избранное';
  if(state.search.trim())return`Поиск: ${state.search.trim()}`;
  if(state.categoryCode!=='all')return categoryLabel(state.categoryCode);
  if(state.categoryMain!=='all')return CATEGORY_TREE.find(main=>main.id===state.categoryMain)?.label||'Все товары';
  return'Все товары';
}
function primaryCategoryCode(product){if(state.categoryCode!=='all'&&categoryCodes(product).includes(state.categoryCode))return state.categoryCode;const main=state.categoryMain!=='all'?CATEGORY_TREE.find(item=>item.id===state.categoryMain):null;return categoryCodes(product).find(code=>main?.codes.includes(code))||categoryCodes(product)[0]||'13'}
function categoryTrail(product){const code=primaryCategoryCode(product),entry=CATEGORY_BY_CODE.get(code);return entry?{code,main:entry.main,label:entry.label}:{code:'13',main:CATEGORY_TREE[0],label:'Декор и аксессуары'}}
function productCategoryButton(product){const primary=primaryCategoryCode(product),codes=[primary,...categoryCodes(product)].filter((code,index,items)=>CATEGORY_BY_CODE.has(code)&&items.indexOf(code)===index);const visible=codes.length?codes:[categoryTrail(product).code];return`<div class="product-categories" aria-label="Категории товара">${visible.map(code=>{const entry=CATEGORY_BY_CODE.get(code),target=entry.main.children.length?`data-category-code="${escapeAttr(code)}"`:`data-main-category="${escapeAttr(entry.main.id)}"`;return`<button class="product-type product-category-link" type="button" ${target} aria-label="Показать категорию «${escapeAttr(categoryLabel(code))}»">${escapeHtml(categoryLabel(code))}</button>`}).join('')}</div>`}
function detailCategoryTemplate(product){const trail=categoryTrail(product);return`<nav class="detail-breadcrumbs" aria-label="Категории товара"><button type="button" data-main-category="${escapeAttr(trail.main.id)}">${escapeHtml(trail.main.label)}</button>${trail.main.children.length?`<span aria-hidden="true">›</span><button type="button" data-category-code="${escapeAttr(trail.code)}">${escapeHtml(trail.label)}</button>`:''}</nav>`}

const COMPUTER_CHAIR_CATEGORY='Компьютерные кресла',COMPUTER_CHAIR_LABEL='Компьютерное кресло',BEDROOM_CATEGORY='Кровати и мебель для спальни',RATTAN_CATEGORY='Ротанг',OUTDOOR_FURNITURE_CATEGORY='Садовая мебель, ковка',OUTDOOR_FURNITURE_TERMS='уличная мебель садовая мебель дачная мебель мебель для террас мебель для кафе кованая мебель ковка',RATTAN_TERMS='ротанг мебель из ротанга';
const CONSTRUCTION_MARKERS=[
  {key:'swivel-360',label:'поворотная опора 360°',pattern:/опора\s*360(?:\s*°)?/i},
  {key:'swivel',label:'поворотная основа',pattern:/(?:поворотн|вращающ)[а-яё]*/i},
  {key:'runners',label:'опора-полозья',pattern:/полоз[а-яё]*/i},
  {key:'casters',label:'на колёсах',pattern:/(?:колес|крестовин|газлифт)[а-яё]*/i},
  {key:'armrests',label:'с подлокотниками',pattern:/с\s+подлокотник[а-яё]*/i},
  {key:'no-armrests',label:'без подлокотников',pattern:/без\s+подлокотник[а-яё]*/i},
  {key:'folding',label:'складная конструкция',pattern:/(?:раскладн|складн)[а-яё]*/i}
];
function constructionDescriptor(product){const text=[product.name,...(product.variants||[]).map(v=>`${v.specs||''} ${v.label||''}`)].join(' ').toLocaleLowerCase('ru-RU'),markers=CONSTRUCTION_MARKERS.filter(marker=>marker.pattern.test(text));return{key:markers.map(marker=>marker.key).join('|')||'standard',label:markers.map(marker=>marker.label).join(' · ')}}
const isComputerChair=product=>/^кресла\s+tetchair(?:\s|$)/i.test(product.collection||'');
function outdoorCatalogText(product){return[product.name,product.category,product.collection,product.searchText,...(product.variants||[]).flatMap(variant=>[variant.label,variant.specs])].filter(Boolean).join(' ')}
function isRattanFurniture(product){const text=outdoorCatalogText(product);return product.category===RATTAN_CATEGORY||/(?:^|[^а-яё])ротанг[а-яё]*(?:$|[^а-яё])/iu.test(text)}
function isForgedOutdoorFurniture(product){const text=outdoorCatalogText(product);return/(?:^|[^а-яё])ковк[а-яё]*(?:$|[^а-яё])/iu.test(text)}
function enrichCatalogProduct(product){
  const computerChair=isComputerChair(product),bedroom=product.category==='Спальня',rattan=isRattanFurniture(product),outdoor=isForgedOutdoorFurniture(product),construction=constructionDescriptor(product);
  const searchTerms=[computerChair?'компьютерное кресло компьютерные кресла офисное кресло офисные кресла':'',rattan?RATTAN_TERMS:'',outdoor?OUTDOOR_FURNITURE_TERMS:''].filter(Boolean).join(' ');
  const assignedCodes=[...new Set((product.variants||[]).flatMap(variant=>state.categoryAssignments[String(variant.sourceId)]||[]))];
  const codes=categoryCodes(product).length?categoryCodes(product):assignedCodes.length?assignedCodes:computerChair?['12']:bedroom?['11']:rattan?['10']:outdoor?['9']:['13'];
  return {...product,categoryCodes:codes,category:categoryLabel(codes[0])||product.category,constructionKey:construction.key,kindLabel:categoryLabel(codes[0]),searchTerms};
}
function normalizeCatalogProducts(products){
  return products.map((product,index)=>{
    const variants=product.variants||[];
    return enrichCatalogProduct({...product,name:stripPackaging(product.name),variants,variantCount:variants.length,_index:index,_selected:variants[0]?.sourceId});
  });
}
async function init(){try{const[indexResponse,categoryResponse]=await Promise.all([fetch(DATA_BASE+'catalog-index.json',{cache:'no-cache'}),fetch(DATA_BASE+'category-assignments.json',{cache:'no-cache'})]);if(!indexResponse.ok||!categoryResponse.ok)throw Error(`HTTP ${indexResponse.status}/${categoryResponse.status}`);const[d,categories]=await Promise.all([indexResponse.json(),categoryResponse.json()]);state.categoryAssignments=categories.assignments||{};state.products=normalizeCatalogProducts(d.products);window.auditVariantPresentation?.(state.products);restoreSharedState();expandedMobileCategory=state.categoryMain==='all'?null:state.categoryMain;renderCategories();applyFilters();updateCounters();renderRecent();$('#searchForm')?.addEventListener('submit',submitSearch);const q=hashParams(),snapshot=catalogSnapshot();if(q.get('product'))await openProduct(q.get('product'),q.get('variant'),{historyMode:'direct'});else history.replaceState({view:'catalog',catalog:snapshot,scrollY:scrollY},'',catalogUrl(snapshot));if(q.get('view')==='cart'&&Object.keys(state.cart).length){renderCart();els.cartDialog.showModal();document.body.style.overflow='hidden'}}catch(e){console.error('[catalog-index]',e);els.count.hidden=false;els.count.textContent='Каталог временно недоступен';els.empty.hidden=false}}
function restoreSharedState(){const q=hashParams();if(CATEGORY_TREE.some(item=>item.id===q.get('main')))state.categoryMain=q.get('main');if(CATEGORY_BY_CODE.has(q.get('category'))){const main=categoryMainFor(q.get('category'));state.categoryMain=main.id;state.categoryCode=main.children.length?q.get('category'):'all'}state.page=Math.max(1,Number(q.get('page'))||1);state.search=q.get('q')||'';state.sort=['featured','price-asc','price-desc','name'].includes(q.get('sort'))?q.get('sort'):'featured';$('#searchInput').value=state.search;$('#sortSelect').value=state.sort;if(q.get('favorites')){state.favorites=q.get('favorites').split('~').filter(id=>state.products.some(p=>p.id===id));storage.write('forma:favorites',state.favorites);state.view='favorites'}if(q.get('cart')){const cart={};q.get('cart').split('~').forEach(x=>{const[id,qty]=x.split('.');if(/^\d+$/.test(id))cart[id]=Math.max(1,Number(qty)||1)});if(Object.keys(cart).length){state.cart=cart;storage.write('forma:cart',cart)}}}
function variantCategoryCodes(product,variant){const assigned=(state.categoryAssignments[String(variant.sourceId)]||[]).map(String);return assigned.length?assigned:categoryCodes(product)}
function categoryVariantCount(codes=null){return state.products.reduce((count,product)=>count+(product.variants||[]).reduce((sum,variant)=>sum+(!codes||variantCategoryCodes(product,variant).some(code=>codes.includes(code))?1:0),0),0)}
function renderCategories(){
  const primary=`<div class="category-primary" role="group" aria-label="Основные категории"><button class="category-main ${state.categoryMain==='all'?'active':''}" data-main-category="all"><span class="category-icon" aria-hidden="true">∞</span><span data-mobile-label="${MOBILE_CATEGORY_LABELS.all}">Все товары</span><small>${categoryVariantCount()}</small></button>${CATEGORY_TREE.map(main=>`<button class="category-main ${state.categoryMain===main.id?'active':''}" data-main-category="${main.id}"><span class="category-icon" aria-hidden="true">${main.icon}</span><span data-mobile-label="${MOBILE_CATEGORY_LABELS[main.id]}">${main.label}</span><small>${categoryVariantCount(main.codes)}</small></button>`).join('')}</div>`;
  const current=CATEGORY_TREE.find(main=>main.id===state.categoryMain),secondary=current?.children.length?`<div class="category-secondary"><button class="subcat ${state.categoryCode==='all'?'active':''}" data-category-code="all">Все</button>${current.children.map(([code,label])=>`<button class="subcat ${state.categoryCode===code?'active':''}" data-category-code="${code}">${label}<small>${categoryVariantCount([code])}</small></button>`).join('')}</div>`:'';
  const mobile=`<div class="mobile-category-list" aria-label="Категории товаров"><section class="mobile-category-section mobile-category-all"><button type="button" class="mobile-category-trigger ${state.categoryMain==='all'&&state.categoryCode==='all'?'active':''}" data-mobile-all-products aria-pressed="${state.categoryMain==='all'&&state.categoryCode==='all'?'true':'false'}"><span class="mobile-category-all-icon" aria-hidden="true"><svg viewBox="0 0 24 24" fill="none"><path d="M4 7h16M4 12h16M4 17h16" stroke="currentColor" stroke-width="1.7" stroke-linecap="round"/><circle cx="7" cy="7" r="1.7" fill="currentColor"/><circle cx="13" cy="12" r="1.7" fill="currentColor"/><circle cx="9" cy="17" r="1.7" fill="currentColor"/></svg></span><span class="mobile-category-all-label">Все товары</span><span class="mobile-category-count">${categoryVariantCount()}</span><span class="mobile-subcategory-chevron" aria-hidden="true"></span></button></section>${CATEGORY_TREE.map(main=>{const open=expandedMobileCategory===main.id,active=state.categoryMain===main.id;return`<section class="mobile-category-section ${open?'open':''} ${active?'active':''}" data-mobile-section="${main.id}"><button type="button" class="mobile-category-trigger ${active?'active':''}" data-mobile-category-toggle="${main.id}" aria-expanded="${open?'true':'false'}"><span class="mobile-category-icon" aria-hidden="true">${main.icon}</span><span class="mobile-category-name">${MOBILE_CATEGORY_LABELS[main.id]}</span><span class="mobile-category-count">${categoryVariantCount(main.codes)}</span><span class="mobile-category-chevron" aria-hidden="true"></span></button><div class="mobile-subcategory-list" ${open?'':'hidden'}><button type="button" class="mobile-subcategory ${active&&state.categoryCode==='all'?'active':''}" data-mobile-main="${main.id}" data-mobile-code="all"><span>${MOBILE_ALL_LABELS[main.id]}</span><small>${categoryVariantCount(main.codes)}</small><span class="mobile-subcategory-chevron" aria-hidden="true"></span></button>${main.children.map(([code,label])=>`<button type="button" class="mobile-subcategory ${active&&state.categoryCode===code?'active':''}" data-mobile-main="${main.id}" data-mobile-code="${code}"><span>${label}</span><small>${categoryVariantCount([code])}</small><span class="mobile-subcategory-chevron" aria-hidden="true"></span></button>`).join('')}</div></section>`}).join('')}</div>`;
  els.categories.innerHTML=primary+(secondary||'')+mobile;
}
function catalogSnapshot(){return{categoryMain:state.categoryMain,categoryCode:state.categoryCode,search:state.search,sort:state.sort,page:state.page,min:state.min,max:state.max,multi:state.multi,view:state.view,expandedMobileCategory}}
function restoreCatalogSnapshot(s){if(!s)return;state.categoryMain=s.categoryMain||'all';state.categoryCode=s.categoryCode||'all';state.search=s.search||'';state.sort=s.sort||'featured';state.page=s.page||1;state.min=s.min||'';state.max=s.max||'';state.multi=!!s.multi;state.view=s.view||'catalog';expandedMobileCategory=s.expandedMobileCategory??(state.categoryMain==='all'?null:state.categoryMain);$('#searchInput').value=state.search;$('#sortSelect').value=state.sort;$('#priceMin').value=state.min;$('#priceMax').value=state.max;$('#multiVariant').checked=state.multi;renderCategories();applyFilters(false)}
function catalogUrl(s=catalogSnapshot()){const q=new URLSearchParams();if(s.categoryMain!=='all')q.set('main',s.categoryMain);if(s.categoryCode!=='all')q.set('category',s.categoryCode);if(s.search)q.set('q',s.search);if(s.sort!=='featured')q.set('sort',s.sort);if(s.page>1)q.set('page',s.page);if(s.view==='favorites'&&state.favorites.length)q.set('favorites',state.favorites.join('~'));const qs=q.toString();return baseUrl()+(qs?'#'+qs:'')}
function syncCatalogHistory(mode='replace',scrollYValue=scrollY){const s=catalogSnapshot(),payload={view:'catalog',catalog:s,scrollY:scrollYValue};if(mode==='push')history.pushState(payload,'',catalogUrl(s));else history.replaceState(payload,'',catalogUrl(s))}
function productUrl(id,variantId){const q=new URLSearchParams({product:id});if(variantId)q.set('variant',variantId);return`${baseUrl()}#${q}`}

function applyFilters(resetPage=true){
  if(resetPage)state.page=1;
  let p=[...state.products];
  if(state.view==='favorites')p=p.filter(x=>state.favorites.includes(x.id));
  if(state.categoryMain!=='all'){const main=CATEGORY_TREE.find(x=>x.id===state.categoryMain);p=p.filter(x=>categoryCodes(x).some(code=>main?.codes.includes(code)))}
  if(state.categoryCode!=='all')p=p.filter(x=>categoryCodes(x).includes(state.categoryCode));
  if(state.search.trim()){const q=state.search.trim().toLocaleLowerCase('ru-RU');p=p.filter(x=>(`${x.name} ${x.category} ${x.collection||''} ${x.searchTerms||''} ${x.variants.map(v=>`${v.label||''} ${v.specs||''}`).join(' ')}`).toLocaleLowerCase('ru-RU').includes(q))}
  if(state.min)p=p.filter(x=>minPrice(x)>=Number(state.min));
  if(state.max)p=p.filter(x=>minPrice(x)<=Number(state.max));
  if(state.multi)p=p.filter(x=>x.variants.length>1);
  if(state.sort==='price-asc')p.sort((a,b)=>minPrice(a)-minPrice(b));
  if(state.sort==='price-desc')p.sort((a,b)=>minPrice(b)-minPrice(a));
  if(state.sort==='name')p.sort((a,b)=>a.name.localeCompare(b.name,'ru'));
  if(state.sort==='featured')p.sort((a,b)=>a._index-b._index);
  state.filtered=p;renderCatalog();renderCategories();updateCount();
}
function updateCount(){els.count.textContent=`${state.filtered.length} ${plural(state.filtered.length,'модель','модели','моделей')}`;els.count.hidden=false;els.title.textContent=currentCatalogTitle();els.favoritesToolbar.hidden=state.view!=='favorites';els.shareFavorites.hidden=state.view!=='favorites'||!state.favorites.length}
function activeVariant(product){return currentVariant(product,product._selected)}
function cardTemplate(product){const v=activeVariant(product),favorite=state.favorites.includes(product.id),retail=Number(v.retailPrice)>Number(v.wholesalePrice);return`<article class="product-card" data-product-card="${escapeAttr(product.id)}">${productImageStage(product,v,favorite)}<div class="product-info"><button class="product-name" type="button" data-open="${escapeAttr(product.id)}">${escapeHtml(stripModel(product.name))}</button>${productCategoryButton(product)}<p class="product-meta">${escapeHtml(variantLabel(v))}</p>${product.variants.length>1?`<div class="card-variants">${product.variants.slice(0,8).map(x=>`<button class="card-swatch ${String(x.sourceId)===String(v.sourceId)?'active':''}" style="--swatch:${colorFor(variantLabel(x))}" data-card-variant="${x.sourceId}" data-product="${escapeAttr(product.id)}" title="${escapeAttr(variantLabel(x))}"></button>`).join('')}</div>`:''}<div class="product-bottom"><span class="price-stack"><small>Оптовая цена</small><strong class="product-price">${money(v.wholesalePrice)}</strong>${retail?`<span>Розничная цена <del>${money(v.retailPrice)}</del></span>`:''}</span><button class="quick-add" data-add="${escapeAttr(product.id)}" data-source="${v.sourceId}">Добавить в заказ</button></div></div></article>`}
function productImageStage(product,variant,favorite){const images=(variant.images?.length?variant.images:[variant.primaryImage]).filter(Boolean).slice(0,12),src=images[0]||variant.primaryImage||'',canCycle=images.length>1;return`<div class="product-image-stage" data-open="${escapeAttr(product.id)}" data-card-gallery data-source="${variant.sourceId}" data-gallery-index="0" tabindex="0" role="button" aria-label="Открыть ${escapeAttr(stripModel(product.name))}"><img src="${escapeAttr(imageUrl(src))}" alt="${escapeAttr(stripModel(product.name))}" loading="lazy" onerror="this.remove()"><button class="favorite ${favorite?'active':''}" data-favorite="${escapeAttr(product.id)}" aria-label="${favorite?'Убрать из избранного':'Добавить в избранное'}">${favorite?'♥':'♡'}</button>${canCycle?`<button class="card-arrow card-arrow-prev" type="button" data-card-gallery-step="-1" aria-label="Предыдущее фото">‹</button><button class="card-arrow card-arrow-next" type="button" data-card-gallery-step="1" aria-label="Следующее фото">›</button>`:''}<script type="application/json" class="card-gallery-data">${escapeHtml(JSON.stringify(images.map(imageUrl)))}</script></div>`}
function renderCatalog(){const start=(state.page-1)*PAGE_SIZE,rows=state.filtered.slice(start,start+PAGE_SIZE);els.grid.innerHTML=rows.map(cardTemplate).join('');els.empty.hidden=!!rows.length;renderPages()}
function renderPages(){const n=Math.ceil(state.filtered.length/PAGE_SIZE);els.pages.innerHTML=n<=1?'':Array.from({length:n},(_,i)=>`<button class="${state.page===i+1?'active':''}" data-page="${i+1}">${i+1}</button>`).join('')}
function replaceCatalogCard(product){if(!product)return false;const current=els.grid?.querySelector(`.product-card[data-product-card="${CSS.escape(product.id)}"]`);if(!current)return false;const template=document.createElement('template');template.innerHTML=cardTemplate(product).trim();const next=template.content.firstElementChild;if(!next)return false;current.replaceWith(next);return true}

async function getFullProduct(product){if(!product)return null;if(els.detailCache?.has?.(product.id))return els.detailCache.get(product.id);if(state.detailCache.has(product.id))return state.detailCache.get(product.id);try{const r=await fetch(`${DATA_BASE}details/${product.id}.json`,{cache:'no-cache'});if(!r.ok)throw Error(`HTTP ${r.status}`);const full=await r.json();full._selected=product._selected;full.categoryCodes=product.categoryCodes;state.detailCache.set(product.id,full);return full}catch(e){console.warn('[detail]',e);return product}}
function detailTemplate(product,v){const images=(v.images?.length?v.images:[v.primaryImage]).filter(Boolean);return`<article class="detail" data-detail-id="${escapeAttr(product.id)}">${detailCategoryTemplate(product)}<div class="gallery"><img class="gallery-main" id="galleryMain" src="${escapeAttr(imageUrl(images[0]))}" alt="${escapeAttr(stripModel(product.name))}"><div class="thumbnails">${images.map((src,i)=>`<button class="thumbnail ${i===0?'active':''}" data-image="${escapeAttr(imageUrl(src))}"><img src="${escapeAttr(imageUrl(src))}" alt="Фото ${i+1}"></button>`).join('')}</div></div><div class="detail-copy"><h2>${escapeHtml(stripModel(product.name))}</h2><p class="product-meta">${escapeHtml(variantLabel(v))}</p><div class="detail-prices"><strong class="detail-price">${money(v.wholesalePrice)}</strong>${Number(v.retailPrice)>Number(v.wholesalePrice)?`<span>Розничная цена <del>${money(v.retailPrice)}</del></span>`:''}</div>${product.variants.length>1?`<div class="variant-options">${product.variants.map(x=>`<button class="variant-option ${String(x.sourceId)===String(v.sourceId)?'active':''}" data-variant="${x.sourceId}">${escapeHtml(variantLabel(x))}</button>`).join('')}</div>`:''}<div class="variant-section"><div class="variant-label"><strong>Характеристики и размеры</strong><span>арт. ${v.sourceId}</span></div><p class="specs">${escapeHtml(v.specs||'')}</p></div><div class="detail-sticky-actions"><button class="primary-button" data-add="${escapeAttr(product.id)}" data-source="${v.sourceId}">Добавить в заказ</button><button class="share-button" data-share-product="${escapeAttr(product.id)}" data-source="${v.sourceId}">Поделиться</button></div></div></article>`}
async function openProduct(id,variantId,{historyMode='push'}={}){const p=state.products.find(x=>x.id===id);if(!p)return;const full=await getFullProduct(p);const v=currentVariant(full,variantId||p._selected);p._selected=v.sourceId;full._selected=v.sourceId;if(historyMode==='push')history.pushState({view:'product',productId:p.id,variantId:v.sourceId,catalog:catalogSnapshot(),scrollY:scrollY},'',productUrl(p.id,v.sourceId));else if(historyMode==='direct')history.replaceState({view:'product',productId:p.id,variantId:v.sourceId,catalog:catalogSnapshot(),scrollY:0},'',productUrl(p.id,v.sourceId));els.detail.innerHTML=detailTemplate(full,v);els.productDialog.showModal();document.body.style.overflow='hidden';if(!state.recent.includes(p.id)){state.recent.unshift(p.id);state.recent=state.recent.slice(0,12);storage.write('forma:recent',state.recent);renderRecent()}}
function closeProduct({viaHistory=true}={}){if(els.productDialog.open)els.productDialog.close();document.body.style.overflow='';if(viaHistory&&history.state?.view==='product')history.back()}

function toggleFavorite(id){const active=!state.favorites.includes(id);state.favorites=active?[id,...state.favorites]:state.favorites.filter(x=>x!==id);storage.write('forma:favorites',state.favorites);applyFilters(false);updateCounters();toast(active?'Добавили в избранное':'Убрали из избранного')}
function cartRows(){const map=new Map(state.products.flatMap(p=>p.variants.map(v=>[String(v.sourceId),{product:p,variant:v}])));return Object.entries(state.cart).map(([key,qty])=>({...map.get(key),key,qty})).filter(x=>x.variant)}
function orderText(rows=cartRows(),total=rows.reduce((s,x)=>s+x.variant.wholesalePrice*x.qty,0)){return`Здравствуйте! Хочу оформить заказ в FORMA HOME:\n${rows.map(x=>`• ${stripModel(x.product.name)} — ${variantLabel(x.variant)}, арт. ${x.variant.sourceId}, ${x.qty} шт.`).join('\n')}\nИтого: ${money(total)}\n\nОкончательное наличие и срок отгрузки подтвердит менеджер после получения заявки.`}
const cartShareUrl=()=>`${baseUrl()}#view=cart&cart=${Object.entries(state.cart).map(([id,q])=>`${id}.${q}`).join('~')}`,favoritesShareUrl=()=>`${baseUrl()}#view=favorites&favorites=${state.favorites.join('~')}`;
function renderCart(){const rows=cartRows();els.cartItems.innerHTML=rows.length?`<div class="cart-list">${rows.map(({product:p,variant:v,key,qty})=>`<article class="cart-item" data-open="${escapeAttr(p.id)}" data-source="${v.sourceId}"><img src="${escapeAttr(imageUrl(v.primaryImage))}" alt=""><div><h3>${escapeHtml(stripModel(p.name))}</h3><p>${escapeHtml(variantLabel(v))}<br>арт. ${v.sourceId}</p><div class="qty"><button data-qty="${key}" data-delta="-1">−</button><span>${qty}</span><button data-qty="${key}" data-delta="1">+</button></div></div><div><strong>${money(v.wholesalePrice*qty)}</strong><button class="remove" data-remove="${key}">Удалить</button></div></article>`).join('')}</div>`:'<div class="cart-empty"><h3>Корзина пока пуста</h3></div>';const total=rows.reduce((s,x)=>s+x.variant.wholesalePrice*x.qty,0),share=cartShareUrl(),order=orderText(rows,total),mailSubject=encodeURIComponent('Заказ FORMA HOME'),mailBody=encodeURIComponent(order+'\n\nСсылка на собранную корзину:\n'+share);els.cartFooter.innerHTML=rows.length?`<div class="cart-total"><span>Итого</span><span>${money(total)}</span></div><p class="availability-note">Окончательное наличие и срок отгрузки подтвердит менеджер после получения заявки.</p><div class="checkout-actions"><a class="primary-button" href="${directContactUrl('whatsapp',order+'\n'+share)}" target="_blank" rel="noopener">Заказать в WhatsApp</a><a class="messenger-button" href="${directContactUrl('telegram',order+'\n'+share)}" target="_blank" rel="noopener">Заказать в Telegram</a><a class="messenger-button" href="mailto:${ORDER_EMAIL}?subject=${mailSubject}&body=${mailBody}">Заказать по e-mail</a><button class="share-button" data-share-cart>Поделиться корзиной</button></div>`:''}
async function sharePayload(title,text,url){if(navigator.share){try{await navigator.share({title,text,url})}catch{}}else{await navigator.clipboard?.writeText(url);toast('Ссылка скопирована')}}
function recentCardTemplate(p){const v=currentVariant(p,p._selected),favorite=state.favorites.includes(p.id),retail=Number(v.retailPrice)>Number(v.wholesalePrice);return`<article class="recent-card"><button class="recent-image" data-open="${escapeAttr(p.id)}" aria-label="Открыть ${escapeAttr(stripModel(p.name))}"><img src="${escapeAttr(imageUrl(v.primaryImage))}" alt="${escapeAttr(stripModel(p.name))}" loading="lazy" onerror="this.remove()"></button><div class="recent-info"><button class="recent-favorite ${favorite?'active':''}" data-favorite="${escapeAttr(p.id)}" aria-label="${favorite?'Убрать из избранного':'Добавить в избранное'}"></button><button class="recent-name" data-open="${escapeAttr(p.id)}">${escapeHtml(stripModel(p.name))}</button><p class="recent-variant">${escapeHtml(variantLabel(v))}</p><div class="recent-bottom"><span class="recent-prices"><strong>${money(v.wholesalePrice)}</strong>${retail?`<del>${money(v.retailPrice)}</del>`:''}</span><button class="recent-add" data-add="${escapeAttr(p.id)}" data-source="${v.sourceId}">В корзину</button></div></div></article>`}
function renderRecent(){const p=state.recent.map(id=>state.products.find(x=>x.id===id)).filter(Boolean).slice(0,5);$('#recentSection').hidden=!p.length;$('#recentRow').innerHTML=p.map(recentCardTemplate).join('')}
function resetFilters(){state.view='catalog';state.categoryMain='all';state.categoryCode='all';state.search='';state.min='';state.max='';state.multi=false;state.page=1;expandedMobileCategory=null;$('#searchInput').value='';$('#priceMin').value='';$('#priceMax').value='';$('#multiVariant').checked=false;renderCategories();applyFilters();syncCatalogHistory()}function toast(m){els.toast.textContent=m;els.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>els.toast.classList.remove('show'),1800)}
function submitSearch(event){event?.preventDefault();state.search=$('#searchInput').value.trim();state.view='catalog';state.page=1;applyFilters();syncCatalogHistory('push');$('#catalogTitle')?.scrollIntoView({behavior:'smooth',block:'start'})}
function updateCounters(){$('#favoritesCount').textContent=state.favorites.length;$('#cartCount').textContent=Object.values(state.cart).reduce((s,x)=>s+x,0);$('#cartCount').hidden=!Object.keys(state.cart).length;$('#favoritesCount').hidden=!state.favorites.length}

document.addEventListener('click',async e=>{
  const favorite=e.target.closest('[data-favorite]');if(favorite){e.stopPropagation();toggleFavorite(favorite.dataset.favorite);return}
  const add=e.target.closest('[data-add]');if(add){const key=String(add.dataset.source);state.cart[key]=(state.cart[key]||0)+1;storage.write('forma:cart',state.cart);updateCounters();toast('Добавили в заказ');return}
  const variant=e.target.closest('[data-card-variant]');if(variant){e.stopPropagation();const p=state.products.find(x=>x.id===variant.dataset.product);if(p&&String(p._selected)!==String(variant.dataset.cardVariant)){p._selected=variant.dataset.cardVariant;replaceCatalogCard(p)}return}
  const category=e.target.closest('[data-category-code]');if(category){state.categoryCode=category.dataset.categoryCode;if(state.categoryCode!=='all')state.categoryMain=categoryMainFor(state.categoryCode).id;state.view='catalog';state.page=1;applyFilters();syncCatalogHistory('push');return}
  const main=e.target.closest('[data-main-category]');if(main){state.categoryMain=main.dataset.mainCategory;state.categoryCode='all';state.view='catalog';state.page=1;expandedMobileCategory=state.categoryMain==='all'?null:state.categoryMain;applyFilters();syncCatalogHistory('push');return}
  const mobileAll=e.target.closest('[data-mobile-all-products]');if(mobileAll){resetFilters();return}
  const mobileToggle=e.target.closest('[data-mobile-category-toggle]');if(mobileToggle){const id=mobileToggle.dataset.mobileCategoryToggle;expandedMobileCategory=expandedMobileCategory===id?null:id;renderCategories();return}
  const mobileSub=e.target.closest('[data-mobile-main][data-mobile-code]');if(mobileSub){state.categoryMain=mobileSub.dataset.mobileMain;state.categoryCode=mobileSub.dataset.mobileCode;state.view='catalog';state.page=1;expandedMobileCategory=state.categoryMain;applyFilters();syncCatalogHistory('push');return}
  const page=e.target.closest('[data-page]');if(page){state.page=Number(page.dataset.page);renderCatalog();syncCatalogHistory();$('#catalogTitle')?.scrollIntoView({behavior:'smooth',block:'start'});return}
  const imageStep=e.target.closest('[data-card-gallery-step]');if(imageStep){e.preventDefault();e.stopPropagation();const stage=imageStep.closest('[data-card-gallery]'),data=stage?.querySelector('.card-gallery-data');if(!stage||!data)return;let images=[];try{images=JSON.parse(data.textContent||'[]')}catch{}if(!images.length)return;const current=Number(stage.dataset.galleryIndex)||0,next=(current+Number(imageStep.dataset.cardGalleryStep)+images.length)%images.length,img=stage.querySelector('img');stage.dataset.galleryIndex=String(next);if(img)img.src=images[next];return}
  const thumb=e.target.closest('[data-image]');if(thumb){const img=$('#galleryMain');if(img){img.src=thumb.dataset.image;thumb.parentElement.querySelectorAll('.thumbnail').forEach(x=>x.classList.toggle('active',x===thumb))}return}
  const detailVariant=e.target.closest('[data-variant]');if(detailVariant){const article=e.target.closest('[data-detail-id]'),p=state.products.find(x=>x.id===article?.dataset.detailId);if(p){p._selected=detailVariant.dataset.variant;const full=await getFullProduct(p);full._selected=p._selected;els.detail.innerHTML=detailTemplate(full,currentVariant(full,p._selected));history.replaceState({...history.state,variantId:p._selected},'',productUrl(p.id,p._selected))}return}
  const open=e.target.closest('[data-open]');if(open){await openProduct(open.dataset.open,open.dataset.source);return}
  const qty=e.target.closest('[data-qty]');if(qty){const key=qty.dataset.qty;state.cart[key]=Math.max(0,(state.cart[key]||0)+Number(qty.dataset.delta));if(!state.cart[key])delete state.cart[key];storage.write('forma:cart',state.cart);renderCart();updateCounters();return}
  const remove=e.target.closest('[data-remove]');if(remove){delete state.cart[remove.dataset.remove];storage.write('forma:cart',state.cart);renderCart();updateCounters();return}
  const shareProduct=e.target.closest('[data-share-product]');if(shareProduct){const p=state.products.find(x=>x.id===shareProduct.dataset.shareProduct),v=currentVariant(p,shareProduct.dataset.source);sharePayload(stripModel(p.name),`${stripModel(p.name)} — ${variantLabel(v)}, ${money(v.wholesalePrice)}`,productUrl(p.id,v.sourceId));return}
  if(e.target.closest('[data-share-cart]')){sharePayload('Корзина FORMA HOME',orderText(),cartShareUrl());return}
});

$('#searchForm')?.addEventListener('submit',submitSearch);
$('#searchInput')?.addEventListener('input',e=>{if(!e.target.value)state.search=''});
$('#sortSelect')?.addEventListener('change',e=>{state.sort=e.target.value;applyFilters();syncCatalogHistory('push')});
$('#filterToggle')?.addEventListener('click',()=>{$('#filters').classList.toggle('show')});
['priceMin','priceMax'].forEach(id=>$(`#${id}`)?.addEventListener('input',e=>{state[id==='priceMin'?'min':'max']=e.target.value;applyFilters();syncCatalogHistory()}));
$('#multiVariant')?.addEventListener('change',e=>{state.multi=e.target.checked;applyFilters();syncCatalogHistory()});
$('#clearFilters')?.addEventListener('click',resetFilters);$('#emptyReset')?.addEventListener('click',resetFilters);
$('#favoritesButton')?.addEventListener('click',()=>{state.view=state.view==='favorites'?'catalog':'favorites';state.page=1;applyFilters();syncCatalogHistory('push')});
$('#cartButton')?.addEventListener('click',()=>{renderCart();els.cartDialog.showModal();document.body.style.overflow='hidden'});
$('[data-close-cart]')?.addEventListener('click',()=>{els.cartDialog.close();document.body.style.overflow=''});
$('[data-close-dialog]')?.addEventListener('click',()=>closeProduct({viaHistory:true}));
els.productDialog?.addEventListener('close',()=>{document.body.style.overflow=''});
els.cartDialog?.addEventListener('close',()=>{document.body.style.overflow=''});
els.productDialog?.addEventListener('click',e=>{if(e.target===els.productDialog)closeProduct({viaHistory:true})});els.cartDialog?.addEventListener('click',e=>{if(e.target===els.cartDialog){els.cartDialog.close();document.body.style.overflow=''}});
$('#shareFavorites')?.addEventListener('click',()=>sharePayload('Избранное FORMA HOME','Подборка мебели FORMA HOME',favoritesShareUrl()));
window.addEventListener('popstate',event=>{const s=event.state;if(s?.view==='product'){const p=state.products.find(x=>x.id===s.productId);if(p)openProduct(s.productId,s.variantId,{historyMode:'none'});return}if(els.productDialog.open)els.productDialog.close();document.body.style.overflow='';if(s?.view==='catalog'){restoreCatalogSnapshot(s.catalog);requestAnimationFrame(()=>scrollTo(0,s.scrollY||0))}else{const q=hashParams();state.categoryMain=CATEGORY_TREE.some(x=>x.id===q.get('main'))?q.get('main'):'all';state.categoryCode=CATEGORY_BY_CODE.has(q.get('category'))?q.get('category'):'all';state.search=q.get('q')||'';state.sort=['featured','price-asc','price-desc','name'].includes(q.get('sort'))?q.get('sort'):'featured';state.page=Math.max(1,Number(q.get('page'))||1);expandedMobileCategory=state.categoryMain==='all'?null:state.categoryMain;renderCategories();applyFilters(false)}});
init();