const DATA_BASE='./data/',ASSET_BASE='https://gkkm8bm7rn-eng.github.io/tetopt/',PAGE_SIZE=24;
const storage={read(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}},write(k,v){localStorage.setItem(k,JSON.stringify(v))}};
const state={products:[],filtered:[],category:'Все',search:'',sort:'featured',page:1,min:'',max:'',multi:false,view:'catalog',favorites:storage.read('forma:favorites',[]),cart:storage.read('forma:cart',{}),recent:storage.read('forma:recent',[]),detailCache:new Map()};
const $=(s,r=document)=>r.querySelector(s),els={grid:$('#productGrid'),count:$('#resultCount'),categories:$('#categoryRow'),pages:$('#pagination'),empty:$('#emptyState'),detail:$('#productDetail'),productDialog:$('#productDialog'),cartDialog:$('#cartDialog'),cartItems:$('#cartItems'),cartFooter:$('#cartFooter'),toast:$('#toast'),shareFavorites:$('#shareFavorites')};
const money=v=>new Intl.NumberFormat('ru-RU').format(Number(v)||0)+' ₽',imageUrl=p=>!p?'':/^https?:/.test(p)?p:ASSET_BASE+String(p).replace(/^\//,''),stripModel=(n='')=>n.replace(/\s*\(мод\.[^)]+\)\s*/gi,' ').replace(/\s+/g,' ').trim();
const currentVariant=(p,id)=>p.variants.find(v=>String(v.sourceId)===String(id))||p.variants[0],minPrice=p=>Math.min(...p.variants.map(v=>Number(v.wholesalePrice)||Infinity));
const variantLabel=v=>v.label||(v.specs||'').split(',').map(s=>s.trim()).filter(Boolean).slice(-2).join(' · ')||`Вариант ${v.sourceId}`;
const plural=(n,a,b,c)=>n%100>=11&&n%100<=14?c:n%10===1?a:n%10>=2&&n%10<=4?b:c,escapeHtml=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),escapeAttr=escapeHtml;
function colorFor(t=''){const c=[['бел','#f4f1e8'],['черн','#242424'],['сер','#9a9a96'],['беж','#d8c4a7'],['корич','#76513d'],['орех','#8a5a3c'],['натурал','#c49a69'],['золот','#c4a45d'],['зел','#657762'],['син','#526879'],['голуб','#88a9b8'],['красн','#9a473d'],['роз','#c89aa0'],['оранж','#c97943'],['желт','#d2b950'],['хром','#b8bdc0']];return c.find(([k])=>t.toLowerCase().includes(k))?.[1]||'#d8d4ca'} const hardVariant=(t='')=>/металл|дерев|мрамор|хром|каркас|основан|ножк|пластик/i.test(t)&&!/ткан|велюр|экокож|кож|букле|рогож/i.test(t);
const hashParams=()=>new URLSearchParams(location.hash.replace(/^#/,'')),baseUrl=()=>location.href.split('#')[0];

async function init(){try{const r=await fetch(DATA_BASE+'catalog-index.json',{cache:'no-cache'});if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();state.products=d.products.map((p,i)=>({...p,_index:i,_selected:p.variants[0].sourceId}));restoreSharedState();renderCategories();applyFilters();updateCounters();renderRecent();const q=hashParams();if(q.get('product'))await openProduct(q.get('product'),q.get('variant'))}catch(e){console.error('[catalog-index]',e);els.count.textContent='Каталог временно недоступен';els.empty.hidden=false}}
function restoreSharedState(){const q=hashParams();if(q.get('favorites')){state.favorites=q.get('favorites').split('~').filter(id=>state.products.some(p=>p.id===id));storage.write('forma:favorites',state.favorites);state.view='favorites'}if(q.get('cart')){const cart={};q.get('cart').split('~').forEach(x=>{const[id,qty]=x.split('.');if(/^\d+$/.test(id))cart[id]=Math.max(1,Number(qty)||1)});if(Object.keys(cart).length){state.cart=cart;storage.write('forma:cart',cart)}}}
function renderCategories(){const counts=new Map;state.products.forEach(p=>counts.set(p.category,(counts.get(p.category)||0)+1));els.categories.innerHTML=['Все',...Array.from(counts.keys()).sort((a,b)=>a.localeCompare(b,'ru'))].map(c=>`<button class="category-chip ${c===state.category?'active':''}" data-category="${escapeAttr(c)}">${escapeHtml(c)}${c==='Все'?'':` · ${counts.get(c)}`}</button>`).join('')}
function applyFilters(){const q=state.search.trim().toLowerCase();state.filtered=state.products.filter(p=>{const h=p.searchText||[p.name,p.category,p.collection,...p.variants.map(v=>`${v.specs} ${v.sourceId}`)].join(' ').toLowerCase();return(state.view!=='favorites'||state.favorites.includes(p.id))&&(state.category==='Все'||p.category===state.category)&&(!q||h.includes(q))&&(!state.min||minPrice(p)>=Number(state.min))&&(!state.max||minPrice(p)<=Number(state.max))&&(!state.multi||p.variants.length>1)});state.filtered.sort((a,b)=>state.sort==='price-asc'?minPrice(a)-minPrice(b):state.sort==='price-desc'?minPrice(b)-minPrice(a):state.sort==='name'?a.name.localeCompare(b.name,'ru'):a._index-b._index);state.page=Math.min(state.page,Math.max(1,Math.ceil(state.filtered.length/PAGE_SIZE)));renderCatalog()}
function renderCatalog(){const list=state.filtered.slice((state.page-1)*PAGE_SIZE,state.page*PAGE_SIZE);els.count.textContent=`${state.filtered.length} ${plural(state.filtered.length,'модель','модели','моделей')}${state.view==='favorites'?' в избранном':''}`;els.shareFavorites.hidden=state.view!=='favorites'||!state.favorites.length;els.grid.innerHTML=list.map(cardTemplate).join('');els.empty.hidden=!!list.length;renderPagination()}
function cardTemplate(p){const v=currentVariant(p,p._selected);return `<article class="product-card"><div class="product-visual" data-open="${escapeAttr(p.id)}" tabindex="0" role="button" aria-label="Открыть ${escapeAttr(p.name)}"><img src="${escapeAttr(imageUrl(v.primaryImage))}" alt="${escapeAttr(stripModel(p.name))}" loading="lazy" onerror="this.remove()"><button class="favorite ${state.favorites.includes(p.id)?'active':''}" data-favorite="${escapeAttr(p.id)}"> ${state.favorites.includes(p.id)?'♥':'♡'}</button>${p.variants.length>1?`<span class="variant-badge">${p.variants.length} ${plural(p.variants.length,'вариант','варианта','вариантов')}</span>`:''}</div><div class="product-info"><h3 class="product-name">${escapeHtml(stripModel(p.name))}</h3><p class="product-meta">${escapeHtml(variantLabel(v))}</p>${p.variants.length>1?`<div class="card-variants">${p.variants.slice(0,8).map(x=>`<button class="card-swatch ${String(x.sourceId)===String(v.sourceId)?'active':''} ${hardVariant(x.specs)?'hard':''}" style="--swatch:${colorFor(variantLabel(x))}" data-card-variant="${x.sourceId}" data-product="${escapeAttr(p.id)}" title="${escapeAttr(variantLabel(x))}"></button>`).join('')}</div>`:''}<div class="product-bottom"><span class="price-stack"><strong class="product-price">${money(v.wholesalePrice)}</strong>${Number(v.retailPrice)>Number(v.wholesalePrice)?`<del>${money(v.retailPrice)}</del>`:''}</span><button class="quick-add" data-add="${escapeAttr(p.id)}" data-source="${v.sourceId}">В корзину</button></div></div></article>`}
function renderPagination(){const total=Math.ceil(state.filtered.length/PAGE_SIZE);if(total<=1){els.pages.innerHTML='';return}const pages=[];for(let i=1;i<=total;i++)if(i===1||i===total||Math.abs(i-state.page)<=1)pages.push(i);let prev=0;els.pages.innerHTML=pages.map(i=>`${i-prev>1?'<span>…</span>':''}<button class="page-button ${i===state.page?'active':''}" data-page="${i}" aria-current="${i===state.page?'page':'false'}">${i}</button>${(prev=i)&&''}`).join('')}

async function getFullProduct(p){if(state.detailCache.has(p.id))return state.detailCache.get(p.id);const r=await fetch(DATA_BASE+p.detailShard);if(!r.ok)throw Error(`HTTP ${r.status}`);const d=await r.json();Object.values(d.products).forEach(x=>state.detailCache.set(x.id,x));return state.detailCache.get(p.id)||p}
async function openProduct(id,sourceId){const s=state.products.find(p=>p.id===id);if(!s)return;if(!state.recent.includes(id)){state.recent.unshift(id);state.recent=state.recent.slice(0,8);storage.write('forma:recent',state.recent)}els.detail.innerHTML='<div class="detail-loading">Загружаем фотографии…</div>';els.productDialog.showModal();document.body.style.overflow='hidden';try{const p=await getFullProduct(s);p._selected=sourceId||s._selected;els.detail.innerHTML=detailTemplate(p,currentVariant(p,p._selected));renderRecent()}catch{els.detail.innerHTML='<div class="detail-loading">Не удалось загрузить карточку.</div>'}}
function detailTemplate(p,v){const images=(v.images?.length?v.images:[v.primaryImage]).filter(Boolean);return `<article class="detail" data-detail-id="${escapeAttr(p.id)}"><div class="gallery"><img class="gallery-main" id="galleryMain" src="${escapeAttr(imageUrl(images[0]))}" alt="${escapeAttr(stripModel(p.name))}"><div class="thumbnails">${images.map((src,i)=>`<button class="thumbnail ${i===0?'active':''}" data-image="${escapeAttr(imageUrl(src))}"><img src="${escapeAttr(imageUrl(src))}" alt="Фото ${i+1}"></button>`).join('')}</div></div><div class="detail-copy"><p class="eyebrow">${escapeHtml(p.category)}</p><h2>${escapeHtml(stripModel(p.name))}</h2><div class="detail-prices"><strong class="detail-price">${money(v.wholesalePrice)}</strong>${Number(v.retailPrice)>Number(v.wholesalePrice)?`<span>Розничная цена <del>${money(v.retailPrice)}</del></span>`:''}</div>${p.variants.length>1?`<div class="variant-section"><div class="variant-label"><strong>Доступные варианты</strong><span>${p.variants.length}</span></div><div class="variant-options">${p.variants.map(x=>`<button class="variant-option ${hardVariant(x.specs)?'hard':''} ${String(x.sourceId)===String(v.sourceId)?'active':''}" data-variant="${x.sourceId}"><span class="swatch" style="background:${colorFor(variantLabel(x))}"></span>${escapeHtml(variantLabel(x))}</button>`).join('')}</div></div>`:''}<div class="variant-section"><div class="variant-label"><strong>Характеристики и размеры</strong><span>арт. ${v.sourceId}</span></div><p class="specs">${escapeHtml(v.specs||'Характеристики уточняются')}</p></div><div class="detail-actions"><button class="primary-button" data-add="${escapeAttr(p.id)}" data-source="${v.sourceId}">Добавить в корзину</button><button class="share-button" data-share-product="${escapeAttr(p.id)}" data-source="${v.sourceId}">Поделиться</button></div></div></article>`}
async function selectVariant(id,sourceId){const s=state.products.find(p=>p.id===id);s._selected=sourceId;const p=await getFullProduct(s);p._selected=sourceId;els.detail.innerHTML=detailTemplate(p,currentVariant(p,sourceId))}
function closeDialog(d){d.close();document.body.style.overflow=''}
function addToCart(id,sourceId){const p=state.products.find(x=>x.id===id);if(!p)return;const v=currentVariant(p,sourceId||p._selected),k=String(v.sourceId);state.cart[k]=(state.cart[k]||0)+1;storage.write('forma:cart',state.cart);updateCounters();toast('Добавили в корзину')}
function updateCounters(){$('#favoritesCount').textContent=state.favorites.length;$('#cartCount').textContent=Object.values(state.cart).reduce((a,b)=>a+b,0)}
function toggleFavorite(id){state.favorites=state.favorites.includes(id)?state.favorites.filter(x=>x!==id):[...state.favorites,id];storage.write('forma:favorites',state.favorites);updateCounters();applyFilters();toast(state.favorites.includes(id)?'Добавили в избранное':'Убрали из избранного')}
function cartRows(){const map=new Map(state.products.flatMap(p=>p.variants.map(v=>[String(v.sourceId),{product:p,variant:v}])));return Object.entries(state.cart).map(([key,qty])=>({...map.get(key),key,qty})).filter(x=>x.variant)}
function orderText(rows=cartRows(),total=rows.reduce((s,x)=>s+x.variant.wholesalePrice*x.qty,0)){return`Здравствуйте! Хочу оформить заказ в FORMA HOME:\n${rows.map(x=>`• ${stripModel(x.product.name)} — ${variantLabel(x.variant)}, арт. ${x.variant.sourceId}, ${x.qty} шт.`).join('\n')}\nИтого: ${money(total)}`}
const cartShareUrl=()=>`${baseUrl()}#view=cart&cart=${Object.entries(state.cart).map(([id,q])=>`${id}.${q}`).join('~')}`,favoritesShareUrl=()=>`${baseUrl()}#view=favorites&favorites=${state.favorites.join('~')}`;
function renderCart(){const rows=cartRows();els.cartItems.innerHTML=rows.length?`<div class="cart-list">${rows.map(({product:p,variant:v,key,qty})=>`<article class="cart-item"><img src="${escapeAttr(imageUrl(v.primaryImage))}" alt=""><div><h3>${escapeHtml(stripModel(p.name))}</h3><p>${escapeHtml(variantLabel(v))}<br>арт. ${v.sourceId}</p><div class="qty"><button data-qty="${key}" data-delta="-1">−</button><span>${qty}</span><button data-qty="${key}" data-delta="1">+</button></div></div><div><strong>${money(v.wholesalePrice*qty)}</strong><button class="remove" data-remove="${key}">Удалить</button></div></article>`).join('')}</div>`:'<div class="cart-empty"><h3>Корзина пока пуста</h3></div>';const total=rows.reduce((s,x)=>s+x.variant.wholesalePrice*x.qty,0),share=cartShareUrl(),msg=encodeURIComponent(orderText(rows,total)+'\n'+share);els.cartFooter.innerHTML=rows.length?`<div class="cart-total"><span>Итого</span><span>${money(total)}</span></div><div class="checkout-actions"><a class="primary-button" href="https://wa.me/?text=${msg}" target="_blank" rel="noopener">Заказать в WhatsApp</a><a class="messenger-button" href="https://t.me/share/url?url=${encodeURIComponent(share)}&text=${encodeURIComponent(orderText(rows,total))}" target="_blank" rel="noopener">Заказать в Telegram</a><button class="share-button" data-share-cart>Поделиться корзиной</button></div>`:''}
async function sharePayload(title,text,url){if(navigator.share){try{await navigator.share({title,text,url})}catch{}}else{await navigator.clipboard?.writeText(url);toast('Ссылка скопирована')}}
function renderRecent(){const p=state.recent.map(id=>state.products.find(x=>x.id===id)).filter(Boolean).slice(0,5);$('#recentSection').hidden=!p.length;$('#recentRow').innerHTML=p.map(x=>{const v=currentVariant(x,x._selected);return`<article class="recent-card" data-open="${escapeAttr(x.id)}"><img src="${escapeAttr(imageUrl(v.primaryImage))}" alt=""><p>${escapeHtml(stripModel(x.name))}</p></article>`}).join('')}
function resetFilters(){state.view='catalog';state.category='Все';state.search='';state.min='';state.max='';state.multi=false;state.page=1;$('#searchInput').value='';$('#priceMin').value='';$('#priceMax').value='';$('#multiVariant').checked=false;renderCategories();applyFilters()}function toast(m){els.toast.textContent=m;els.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>els.toast.classList.remove('show'),1800)}

document.addEventListener('click',async e=>{const b=e.target.closest('button,[data-open]');if(!b)return;if(b.dataset.category!==undefined){state.category=b.dataset.category;state.page=1;renderCategories();applyFilters()}if(b.dataset.page){state.page=Number(b.dataset.page);renderCatalog();$('#catalog').scrollIntoView()}if(b.dataset.open)await openProduct(b.dataset.open);if(b.dataset.favorite){e.stopPropagation();toggleFavorite(b.dataset.favorite)}if(b.dataset.cardVariant){e.stopPropagation();const p=state.products.find(x=>x.id===b.dataset.product);if(p){p._selected=b.dataset.cardVariant;renderCatalog()}}if(b.dataset.add){e.stopPropagation();addToCart(b.dataset.add,b.dataset.source)}if(b.dataset.variant)await selectVariant(b.closest('[data-detail-id]').dataset.detailId,b.dataset.variant);if(b.dataset.image){$('#galleryMain').src=b.dataset.image;document.querySelectorAll('.thumbnail').forEach(x=>x.classList.toggle('active',x===b))}if(b.hasAttribute('data-close-dialog'))closeDialog(els.productDialog);if(b.hasAttribute('data-close-cart'))closeDialog(els.cartDialog);if(b.dataset.qty){state.cart[b.dataset.qty]=(state.cart[b.dataset.qty]||0)+Number(b.dataset.delta);if(state.cart[b.dataset.qty]<=0)delete state.cart[b.dataset.qty];storage.write('forma:cart',state.cart);updateCounters();renderCart()}if(b.dataset.remove){delete state.cart[b.dataset.remove];storage.write('forma:cart',state.cart);updateCounters();renderCart()}if(b.dataset.shareProduct!==undefined){const p=state.products.find(x=>x.id===b.dataset.shareProduct);await sharePayload(stripModel(p.name),variantLabel(currentVariant(p,b.dataset.source)),`${baseUrl()}#product=${encodeURIComponent(p.id)}&variant=${b.dataset.source}`)}if(b.hasAttribute('data-share-cart'))await sharePayload('Корзина FORMA HOME',orderText(),cartShareUrl())});
$('#searchInput').addEventListener('input',e=>{state.search=e.target.value;state.page=1;applyFilters()});$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;applyFilters()});['priceMin','priceMax'].forEach(id=>$('#'+id).addEventListener('input',e=>{state[id==='priceMin'?'min':'max']=e.target.value.replace(/\D/g,'');state.page=1;applyFilters()}));$('#multiVariant').addEventListener('change',e=>{state.multi=e.target.checked;state.page=1;applyFilters()});$('#filterToggle').addEventListener('click',e=>{const o=$('#filters').classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',o)});$('#clearFilters').addEventListener('click',resetFilters);$('#emptyReset').addEventListener('click',resetFilters);$('#cartButton').addEventListener('click',()=>{renderCart();els.cartDialog.showModal();document.body.style.overflow='hidden'});$('#favoritesButton').addEventListener('click',()=>{state.view='favorites';state.category='Все';state.page=1;renderCategories();applyFilters();$('#catalog').scrollIntoView()});els.shareFavorites.addEventListener('click',()=>sharePayload('Избранное FORMA HOME','Моя подборка мебели',favoritesShareUrl()));els.productDialog.addEventListener('click',e=>{if(e.target===els.productDialog)closeDialog(els.productDialog)});els.cartDialog.addEventListener('click',e=>{if(e.target===els.cartDialog)closeDialog(els.cartDialog)});init();
